### ISSUE TITLE
Issue: L__R (Deobfuscated class name)

### ISSUE THREAD

**Issue by ramkotirapido** [razorpay/razorpay-android-sample-app#101]
Hi,
I am using com.razorpay:checkout:1.4.9 and facing this issue L__R (Deobfuscated class name).

Stacktrace:
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rapido.passenger/com.razorpay.CheckoutActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2547)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)

**Comment by ramkotirapido** [comment]
stack trace:
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
       at org.json.JSONTokener.nextValue(JSONTokener.java:94)
       at org.json.JSONObject.(JSONObject.java:156)
       at org.json.JSONObject.(JSONObject.java:173)
       at com.razorpay.L__R$.(Unknown Source:16)
       at com.razorpay.B_$q$.d__1_(Unknown Source:118)
       at com.razorpay.c__C_.onCreate(Unknown Source:93)
       at com.razorpay.CheckoutActivity.onCreate(Unknown Source:13)
       at android.app.Activity.performCreate(Activity.java:6270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2500)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)

**Comment by balrampandey19** [comment]
hi
I am also facing the Same issue. I am using razor pay 1.5.1

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
       at com.razorpay.l__d$.backPressed(Unknown Source:17076)
       at com.razorpay.r_$Z$.backPressed(Unknown Source:148)
       at com.razorpay.b__J_.onBackPressed(Unknown Source:148)
       at com.razorpay.CheckoutActivity.onBackPressed(Unknown Source:5)
       at android.app.Activity.onKeyUp(Activity.java:2727)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3280)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2997)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2706)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5323)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5276)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4721)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4774)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4740)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4882)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4748)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4939)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4721)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4774)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4740)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4748)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4721)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4774)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4740)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4915)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5160)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2886)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2458)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2449)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2863)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteI`

**Comment by sumedht** [comment]
@balrampandey19 @ramkotirapido Update SDK to latest version. We have fixed it in v1.5.4
