### ISSUE TITLE
Fatal crash on CheckoutActivity

### ISSUE THREAD

**Issue by debugger22** [razorpay/razorpay-android-sample-app#105]
```java
Fatal Exception: java.lang.NoSuchFieldError: No field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in /data/app/com.cityflo.customer-1/base.apk:classes2.dex)
       at com.razorpay.l__d$.setOptions(l__d.java:119)
       at com.razorpay.b__J_.onCreate(b__J_.java:96)
       at com.razorpay.E$_6$.onCreate(E.java:23)
       at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:6977)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Comment by sumedht** [comment]
@debugger22 Which version of SDK u r using?

**Comment by sumedht** [comment]
@debugger22 Any details on this?

**Comment by LakshmiPriyaVikram** [comment]
I am using razorpay sdk version 1.5.2.I am also facing this issue. How can I solve this?

**Comment by LakshmiPriyaVikram** [comment]
> @debugger22 Any details on this?

How u solved this issue? I am using sdk version 1.5.2.

**Comment by mwshubham** [comment]
+1
 We are using implementation 'com.razorpay:checkout:1.5.5'

**Comment by vivekshindhe** [comment]
@mwshubham we are now currently at 1.6.2 version. Could you please update and check?
