### ISSUE TITLE
Crash on CheckoutActivity

### ISSUE THREAD

**Issue by Jasonli1558** [razorpay/razorpay-android-sample-app#106]
We are facing crash issue on Android 5.0 and 4.4 devices suddenly when start to CheckoutActivity with the below error.The SDK version we use is 1.5.5

Caused by android.util.AndroidRuntimeException
requestFeature() must be called before adding content
...
com.razorpay.B$$W$.onCreate (B.java:85)
com.razorpay.b__J_.onCreate (b__J_.java:23)
com.razorpay.CheckoutActivity.onCreate (CheckoutActivity.java:8)
...

**Comment by sumedht** [comment]
@Jasonli1558 Can u share the full crash log?

**Comment by Jasonli1558** [comment]
> @Jasonli1558 Can u share the full crash log?

Caused by android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:324)
       at android.app.Activity.requestWindowFeature(Activity.java:3692)
       at com.razorpay.B$$W$.onCreate(B.java:85)
       at com.razorpay.b__J_.onCreate(b__J_.java:23)
       at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:6034)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2442)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2551)
       at android.app.ActivityThread.access$1000(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5581)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)

**Comment by sumedht** [comment]
@Jasonli1558 Looks like issue is because of ```requestWindowFeature(Window.FEATURE_NO_TITLE);``` we are using.
Will update in next release. 
Is the issue on specific device n getting in some specific scenario or every time it's crashing

**Comment by Jasonli1558** [comment]
@sumedht Crash every time.But the crash didn't occur in one device which system version is 7.0.

**Comment by andylauxugang2** [comment]
Dose this issue is fixed? Our company has this problem and a large of people customer could not use razorpay to payment .  The service is very bad !!!!

**Comment by andylauxugang2** [comment]
Dose any one of razorpay on line ? this issue is for 5 weeks ago. Why your guys do not fixed it and make our customer bad service for us. !!!??

**Comment by sumedht** [comment]
@andylauxugang2 Have not release it yet. Will update you on this asap.

**Comment by andylauxugang2** [comment]
OK , Please give us a time for this issue. It effect our customers thanks

**Comment by andylauxugang2** [comment]
Can you give us a time plan table for the issue. Our customer already very angry for the repayment service on the android app !!

**Comment by Jasonli1558** [comment]
@sumedht the crash has affect our business!Give me a date of the release!!!

**Comment by sumedht** [comment]
@andylauxugang2 @Jasonli1558 It will take possibly around 2-3 days to go live. We will try to do that asap.

**Comment by sumedht** [comment]
@andylauxugang2 @Jasonli1558 It's fixed. can u share your email id? will share .aar separately on priority

**Comment by sumedht** [comment]
@andylauxugang2 @Jasonli1558 you can find new release at
https://github.com/razorpay/razorpay-android/releases/tag/v1.5.6

**Comment by Jasonli1558** [comment]
@sumedht this page of new release shows 404

**Comment by Jasonli1558** [comment]
@sumedht I can't add libraray dependency of 1.5.6
the error is : Failed to resolve: com.razorpay:checkout:1.5.6

**Comment by sumedht** [comment]
@Jasonli1558 Find build from release v1.5.6

**Comment by Jasonli1558** [comment]
@sumedht I dont't want to use it by importing .aar and I can't add remote libraray dependency of 1.5.6
the error is : Failed to resolve: com.razorpay:checkout:1.5.6

**Comment by Jasonli1558** [comment]
@sumedht I can't add remote libraray dependency of 1.5.6 and the error is : Failed to resolve: com.razorpay:checkout:1.5.6
