### ISSUE TITLE
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.razorpay.CheckoutActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by shricky** [razorpay/razorpay-android-sample-app#112]
# TRIED adding progaurd rule, Changing sdk version to 1.5.5. It was working fine but when I merged my projects(importing the other one as library module(not using razorpay in the module)), it started showing this error...
 
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.kdgo.in/com.razorpay.CheckoutActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1618)
        at android.app.Activity.startActivityFromFragment(Activity.java:4392)
        at android.app.Fragment.startActivityForResult(Fragment.java:1100)
        at android.app.Fragment.startActivityForResult(Fragment.java:1084)
        at com.razorpay.Checkout.onCreate(:302)
        at android.app.Fragment.performCreate(Fragment.java:2031)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
        at android.app.BackStackRecord.run(BackStackRecord.java:834)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by sumedht** [comment]
HI @shricky Looks like there is integration issue. U can check out a sample app. also find documentation from https://razorpay.com/docs/payment-gateway/integrations-guide/mobile/android/standard/

**Comment by shricky** [comment]
The integration was working fine for all before merging my apps. After merging of apps I got the issue.

**Comment by shricky** [comment]
I got the answer, thanks to @android killer. i just checked my Manifest files. I had added tool:replace in the <application> tag. I removed it and removed the android:icon & android:roundIcon from the other manifest file so that tool:replace must not be needed. And It works fine now.

**Comment by shricky** [comment]
I got the answer. i just checked my Manifest files. I had added tool:replace in the tag. I removed it and removed the android:icon & android:roundIcon from the other manifest file so that tool:replace must not be needed. And It works fine now.

**Comment by ShubhraRao** [comment]
I am still getting the above error. It works fine when I run the RazorPay app individually. But when it is integrated with other packages, it is giving me this error. Please help me out.

**Comment by vivekshindhe** [comment]
@ShubhraRao Thanks for reaching out to us. 

Is it possible that you are using Razorpay SDK through that library? Or use it in any case? From the logs and the issue told by the issuer of the post, this seems like a proguard issue. Also, are you facing this issue in both debug & release modes?
