### ISSUE TITLE
Unable to start activity: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.G_G

### ISSUE THREAD

**Issue by ArvindKer09** [razorpay/razorpay-android-sample-app#121]
java.lang.RuntimeException: Unable to start activity ComponentInfo{in.frendy.app/com.razorpay.CheckoutActivity}: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.G_G" on path: DexPathList[[zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/base.apk", zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.armeabi_v7a.apk", zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.en.apk", zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/lib/arm, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/base.apk!/lib/armeabi-v7a, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.en.apk!/lib/armeabi-v7a, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6634)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.G_G" on path: DexPathList[[zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/base.apk", zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.armeabi_v7a.apk", zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.en.apk", zip file "/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/lib/arm, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/base.apk!/lib/armeabi-v7a, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.en.apk!/lib/armeabi-v7a, /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.razorpay.O_Y.G_G(:1100)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.razorpay.eb.<clinit>(Unknown Source:1664)
	at com.razorpay.eb.a(Unknown Source:0)
	at com.razorpay.c.f(Unknown Source:13)
	at com.razorpay.i.b(Unknown Source:19)
	at com.razorpay.t.onCreate(Unknown Source:70)
	at com.razorpay.Ca.onCreate(Unknown Source:114)
	at com.razorpay.CheckoutActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:7074)
	at android.app.Activity.performCreate(Activity.java:7065)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
	... 9 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.armeabi_v7a.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
		at dalvik.system.DexFile.<init>(DexFile.java:100)
		at dalvik.system.DexFile.<init>(DexFile.java:74)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:695)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:729)
		at android.app.LoadedApk.getResources(LoadedApk.java:956)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5714)
		at android.app.ActivityThread.-wrap1(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
		... 6 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.en.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
		at dalvik.system.DexFile.<init>(DexFile.java:100)
		at dalvik.system.DexFile.<init>(DexFile.java:74)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:695)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:729)
		at android.app.LoadedApk.getResources(LoadedApk.java:956)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5714)
		at android.app.ActivityThread.-wrap1(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
		... 6 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/in.frendy.app-6JaCLtUU8i_xpQjmYbg4bQ==/split_config.xhdpi.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
		at dalvik.system.DexFile.<init>(DexFile.java:100)
		at dalvik.system.DexFile.<init>(DexFile.java:74)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:695)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:729)
		at android.app.LoadedApk.getResources(LoadedApk.java:956)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5714)
		at android.app.ActivityThread.-wrap1(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
		... 6 more

**Comment by sumedht** [comment]
@ArvindKer09 which version you are using? have u added proguard rules?

**Comment by sumedht** [comment]
@ArvindKer09 Any update on this?

**Comment by ujjwalagrawal17** [comment]
Reproduced the same today. 
Razorpay SDK Version: 1.5.2
compileSdkVersion: 28
Also tried adding the proguard: 

```
-keepattributes *Annotation*
-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}
-optimizations !method/inlining/
-keepclasseswithmembers class * {
public void onPayment*(...);
}

```

**Comment by sumedht** [comment]
@ArvindKer09 closing this as there is no update
