### ISSUE TITLE
Crash on Payment Button

### ISSUE THREAD

**Issue by stigasoft** [razorpay/razorpay-android-sample-app#127]
--------- beginning of crash
10-15 11:32:08.745 2102-2102/com.razorpay.newsampleapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.razorpay.newsampleapp, PID: 2102
    java.lang.AbstractMethodError: abstract method "void com.razorpay.RzpPlugin.isRegistered(android.content.Context)"
        at com.razorpay.r$_Y_.onCreate(:48)
        at com.razorpay.CheckoutActivity.onCreate(:8)
        at android.app.Activity.performCreate(Activity.java:6321)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
        at android.app.ActivityThread.access$1100(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sumedht** [comment]
@stigasoft Can you provide more details like a specific scenario? Looks like it is with our sample app, we tested at our side and it's working

**Comment by mrdishant** [comment]
Try removing razorpay-amazonpay and pay with amazonpay.
