### ISSUE TITLE
Store api key in java file?

### ISSUE THREAD

**Issue by Anshul1507** [razorpay/razorpay-android-sample-app#156]
According to the sample app, we need to declare api key in manifest file. Can we make it like in java file, so as to pass that key from server to secure api key?

I have implemented using version [1.5.16] according to DOCs:
Checkout checkout = new Checkout();
checkout.setKeyID(MY_KEY_HERE);

Still its asking me to use the key in Manifest. What should i do ? I want to set it dynamic.

Please Help!

**Comment by sumedht** [comment]
@Anshul1507 It should allow by setKeyID(..)function. What error u getting?

**Comment by Anshul1507** [comment]
@sumedht If I use by this method, then there is no need to set api key in manifest file?
If yes, then i got the error states like "API_KEY need to be declared in manifest.xml file" <- something like this, even though I am using latest version.

**Comment by rohitkhirid** [comment]
I'm also facing same issue.

`Please set your Razorpay API key in AndroidManifest.xml`

**Comment by Anshul1507** [comment]
Hi @rohitkhirid, i solve this issue for my app, you can check [demo](https://github.com/Anshul1507/Razorpay-Integration) here.

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by Dev-Akash** [comment]
Hi there, 
I also came here for the solution of the above issue, but later on i came to realize that the issue was not with the setting of the key_id with `.setKeyID()` function, rather it was with the parameter `activity` we pass at the time of `Checkout.open()`.

Here is the error log:

2020-12-11 14:40:27.511 5476-5476/com.pareekshahub.quiz E/QuizActivity: Error in starting Razorpay Checkout
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at com.razorpay.U$_z$.a_$P$(:38)
        at com.razorpay.Checkout.open(:15420)
        at com.pareekshahub.quiz.QuizActivity.startPayment(QuizActivity.java:528)
        at com.pareekshahub.quiz.QuizActivity$7.onDataChange(QuizActivity.java:393)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
        at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Can you please tell how can i resolve this issue ?

Thank you !

**Comment by Dev-Akash** [comment]
One more Question, is it okay to keep the api_key in androidManifest.xml file or not ? @sumedht

**Comment by Anshul1507** [comment]
There is an option to set api_key dynamically. you can check [here](https://github.com/Anshul1507/Razorpay-Integration) for demo.
