### ISSUE TITLE
razorpay crashing when start payment

### ISSUE THREAD

**Issue by vairam07** [razorpay/razorpay-android-sample-app#167]
2020-06-22 16:39:47.527 11009-11009/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 11009
    java.lang.AbstractMethodError: abstract method "void com.google.android.gms.tasks.OnSuccessListener.onSuccess(java.lang.Object)"
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by vairam07** [comment]
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function",

**Comment by ImSaumilShah** [comment]
Im getting the same error. can anyone help here or anybody found solution to this?

**Comment by ImSaumilShah** [comment]
currently to solve this issue, i downgraded razorpay dependecy level to 1.5.12. 

this problem is coming in 1.5.17. 

razorpay team please resolve this.


hope this helps.

**Comment by ratnakarreddy641** [comment]
06/30 23:41:04: Launching 'app' on Xiaomi Mi A2.
$ adb shell am start -n "com.xplot.myapplication/com.xplot.myapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7359 on device 'xiaomi-mi_a2-498a021'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Perf: Connecting to perf service.
E/Perf: Fail to get file list com.xplot.myapplication
E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
    Fail to get file list com.xplot.myapplication
    getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
W/t.myapplicatio: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/t.myapplicatio: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/WebViewFactory: Loading com.google.android.webview version 83.0.4103.106 (code 410410683)
W/t.myapplicatio: Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/t.myapplicatio: Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
I/cr_LibraryLoader: Loaded native library version number "83.0.4103.106"
W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
I/cr_CachingUmaRecorder: Flushed 3 samples from 3 histograms.
W/t.myapplicatio: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/chromium: [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
W/t.myapplicatio: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
I/AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
    Build Date                       : 09/28/19
    OpenGL ES Shader Compiler Version: EV031.27.05.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : S L 8.0.11 AArch64
I/AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
W/Chrome_InProcGp: type=1400 audit(0.0:285161): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=31823 scontext=u:r:untrusted_app:s0:c25,c257,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0
W/AdrenoUtils: <ReadGpuID_from_sysfs:194>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
    <ReadGpuID:218>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/divx311
W/VideoCapabilities: Unsupported mime video/divx4
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/Utils: could not parse long range '175-174'
W/Gralloc3: mapper 3.x is not supported
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (7437) crash detected (code -1).
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@85c894b
W/t.myapplicatio: Accessing hidden field Llibcore/io/Libcore;->os:Llibcore/io/Os; (greylist, reflection, allowed)
W/t.myapplicatio: Accessing hidden method Llibcore/io/ForwardingOs;->setenv(Ljava/lang/String;Ljava/lang/String;Z)V (greylist, reflection, allowed)
    Accessing hidden method Llibcore/io/ForwardingOs;->getenv(Ljava/lang/String;)Ljava/lang/String; (greylist, reflection, allowed)
W/t.myapplicatio: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
W/t.myapplicatio: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/DpmTcmClient: RegisterTcmMonitor from: $Proxy0
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chatty: uid=10281(com.xplot.myapplication) identical 2 lines
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.15&library=checkoutjs&platform=android (1)
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (7504) crash detected (code -1).
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f459e27
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chatty: uid=10281(com.xplot.myapplication) identical 3 lines
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.15&library=checkoutjs&platform=android (1)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@324a1aa
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chatty: uid=10281(com.xplot.myapplication) identical 3 lines
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.15&library=checkoutjs&platform=android (1)
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (12928) crash detected (code -1).

**Comment by ratnakarreddy641** [comment]
on clicking PAY button  razorpay loads for a second goes blank and reverts back to app


i have tried v 1.5.15,16,17 also nothing seems working....

> 06/30 23:41:04: Launching 'app' on Xiaomi Mi A2.
> $ adb shell am start -n "com.xplot.myapplication/com.xplot.myapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
> Connected to process 7359 on device 'xiaomi-mi_a2-498a021'.
> Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
> I/Perf: Connecting to perf service.
> E/Perf: Fail to get file list com.xplot.myapplication
> E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
> Fail to get file list com.xplot.myapplication
> getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
> W/t.myapplicatio: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
> W/t.myapplicatio: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
> I/WebViewFactory: Loading com.google.android.webview version 83.0.4103.106 (code 410410683)
> W/t.myapplicatio: Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
> W/t.myapplicatio: Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
> I/cr_LibraryLoader: Loaded native library version number "83.0.4103.106"
> W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
> I/cr_CachingUmaRecorder: Flushed 3 samples from 3 histograms.
> W/t.myapplicatio: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
> W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
> W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
> Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
> W/t.myapplicatio: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
> W/chromium: [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
> W/t.myapplicatio: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
> I/AdrenoGLES: QUALCOMM build : f2ab992, I401605978b
> Build Date : 09/28/19
> OpenGL ES Shader Compiler Version: EV031.27.05.01
> Local Branch :
> Remote Branch :
> Remote Branch :
> Reconstruct Branch :
> Build Config : S L 8.0.11 AArch64
> I/AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
> W/Chrome_InProcGp: type=1400 audit(0.0:285161): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=31823 scontext=u:r:untrusted_app:s0:c25,c257,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0
> W/AdrenoUtils: <ReadGpuID_from_sysfs:194>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
> ReadGpuID:218: Failed to read chip ID from gpu_model. Fallback to use the GSL path
> W/VideoCapabilities: Unsupported mime video/divx
> W/VideoCapabilities: Unsupported mime video/divx311
> W/VideoCapabilities: Unsupported mime video/divx4
> W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
> W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
> W/VideoCapabilities: Unsupported mime video/x-ms-wmv
> W/VideoCapabilities: Unsupported mime video/x-ms-wmv
> W/Utils: could not parse long range '175-174'
> W/Gralloc3: mapper 3.x is not supported
> E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (7437) crash detected (code -1).
> W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@85c894b
> W/t.myapplicatio: Accessing hidden field Llibcore/io/Libcore;->os:Llibcore/io/Os; (greylist, reflection, allowed)
> W/t.myapplicatio: Accessing hidden method Llibcore/io/ForwardingOs;->setenv(Ljava/lang/String;Ljava/lang/String;Z)V (greylist, reflection, allowed)
> Accessing hidden method Llibcore/io/ForwardingOs;->getenv(Ljava/lang/String;)Ljava/lang/String; (greylist, reflection, allowed)
> W/t.myapplicatio: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
> W/t.myapplicatio: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
> D/NetworkSecurityConfig: No Network Security Config specified, using platform default
> I/DpmTcmClient: RegisterTcmMonitor from: $Proxy0
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> I/chatty: uid=10281(com.xplot.myapplication) identical 2 lines
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.15&library=checkoutjs&platform=android (1)
> E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (7504) crash detected (code -1).
> W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f459e27
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> I/chatty: uid=10281(com.xplot.myapplication) identical 3 lines
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.15&library=checkoutjs&platform=android (1)
> W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@324a1aa
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> I/chatty: uid=10281(com.xplot.myapplication) identical 3 lines
> D/skia: --- Failed to create image decoder with message 'unimplemented'
> I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.5.15&library=checkoutjs&platform=android (1)
> E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (12928) crash detected (code -1).

**Comment by mrudultora** [comment]
I was also getting this error. My dependency was **implementation 'com.razorpay:checkout:1.5.18** .

Just downgrade the dependency . I changed it to **implementation 'com.razorpay:checkout:1.5.16** to solve this issue currently.
Hope, this will help you. It worked completely in test mode , and, remember to include proguard rules also...
`-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
-keepattributes JavascriptInterface
-keepattributes *Annotation*
-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}
-optimizations !method/inlining/*
-keepclasseswithmembers class * {
  public void onPayment*(...);
}`

**Comment by ratnakarreddy641** [comment]
just Remove This Line in startPayment Method
options.put("order_id", Order_#j76ujhdu);

This Will Work With Any Dependency I guess !

Worked in Testmode

**Comment by mrudultora** [comment]
@ratnakarreddy641  I also got the same error and I was not using such parameter in options.put()
When I changed the dependency version to a lower one it worked just fine.
So, I think this issue is not because of options.put()

**Comment by ratnakarreddy641** [comment]
> @ratnakarreddy641  I also got the same error and I was not using such parameter in options.put()
> When I changed the dependency version to a lower one it worked just fine.
> So, I think this issue is not because of options.put()

It is not bcoz of options.put().
It is bcoz of order_Id parameter field

Which it need to be connected to ORDERS API  of Razorpay

**Comment by sumedht** [comment]
@vairam07 @ImSaumilShah @ratnakarreddy641 @mrudultora 
Apologise for inconvenience. We have released a stable updated version of SDK 1.6.3 with a crash fix, bug fix, more detail error message & many other fixes/features. Please do update to latest version of SDK.

**Comment by PembaTamang** [comment]
same error with the 1.6.5 sdk
`Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function`
the screen says that there is an error with the payment and when I hit close an IntentReceiver is leaked

```
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@e7ea3a7 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@e7ea3a7 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1707)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1438)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1577)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1550)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:654)
        at com.razorpay.CheckoutPresenterImpl$8.onFinish(CheckoutPresenterImpl.java:775)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by pravin-umardand** [comment]
Still having issue

**Comment by yash13902** [comment]
same even I am having this issue...

**Comment by Er-Sikandar** [comment]
same even I am having this issue...

**Comment by AyyaTech** [comment]
i am also having same issue

E/com.razorpay.checkout: Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function

**Comment by wadjeravi** [comment]
I am also facing the same Issue. 
E/com.razorpay.checkout: Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function

Razorpay SDK version - implementation 'com.razorpay:checkout:1.6.21'

**Comment by wadjeravi** [comment]
Issue resolved for me, I was providing wrong razorpay key ID. Please check below 2 fields if you are passing correctly or not
1) checkout.setKeyID(<razorpay key ID>);
2) options.put("order_id", <order ID generated from razorpay ORder API>);
