### ISSUE TITLE
Android app crashing with following crash log in release build

### ISSUE THREAD

**Issue by pravingaikwad07** [razorpay/razorpay-android-sample-app#172]
Fatal Exception: android.view.InflateException
```
Binary XML file line #27 in com.example:layout/rzp_loader: Error inflating class android.widget.ImageView

Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f070104
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:276)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:813)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
       at android.content.res.Resources.loadDrawable(Resources.java:916)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
       at android.widget.ImageView.<init>(ImageView.java:209)
       at android.widget.ImageView.<init>(ImageView.java:190)
       at android.widget.ImageView.<init>(ImageView.java:186)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:854)
       at android.view.LayoutInflater.createView(LayoutInflater.java:776)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:438)
       at android.app.Dialog.setContentView(Dialog.java:571)
       at com.razorpay.g__v_.Q_$2$(g__v_.java:242)
       at com.razorpay.l__d$.onPageStarted(l__d.java:394)
       at com.razorpay.Y_$B$.onPageStarted(Y_.java:75)
       at com.razorpay.H$_a_.onPageStarted(H.java:29)
       at O7.c(O7.java:2)
       at Do.handleMessage(Do.java:161)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Caused by java.lang.reflect.InvocationTargetException
java.lang.reflect.Constructor.newInstance0

```
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:854)
       at android.view.LayoutInflater.createView(LayoutInflater.java:776)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:438)
       at android.app.Dialog.setContentView(Dialog.java:571)
       at com.razorpay.g__v_.Q_$2$(g__v_.java:242)
       at com.razorpay.l__d$.onPageStarted(l__d.java:394)
       at com.razorpay.Y_$B$.onPageStarted(Y_.java:75)
       at com.razorpay.H$_a_.onPageStarted(H.java:29)
       at O7.c(O7.java:2)
       at Do.handleMessage(Do.java:161)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

```
Caused by android.content.res.Resources$NotFoundException
Drawable (missing name) with resource ID #0x7f070104
```

**Comment by sumedht** [comment]
@pravingaikwad07 Can u provide more details like Razorpay SDK version, Android OS version, Frequency of issue..

**Comment by pravingaikwad07** [comment]
@sumedht Razor pay sdk :    
implementation 'com.razorpay:checkout:1.5.16'
Android Mobile : One Plus 6T
Android Version : 10

**Comment by sumedht** [comment]
@pravingaikwad07 we tried at our end but not able tp reproduced. Can u check with integration in our sample app to make sure it's align with yours. Also can u run same sample app in your device & check if it's reproducible.
https://razorpay.com/docs/payment-gateway/android-integration/standard/
