### ISSUE TITLE
com.razorpay:checkout:1.6.4  bug  error

### ISSUE THREAD

**Issue by 317056658** [razorpay/razorpay-android-sample-app#190]
question1： com.razorpay.checkout: Error reading options!
    org.json.JSONException: No value for send_sms_hash，invoke SDK error，The page won't open。

How to solve the problem?

**Comment by vivekshindhe** [comment]
Hey @317056658 

Thanks for reaching out to us! The error isn't actually a fatal exception. There must be some other issue. But if you want to solve this add this to the json payload

json.put("send_sms_hash",true)

Although, would like to ask you to send the logs as well.

**Comment by 317056658** [comment]
@vivekshindhe   com.razorpay:checkout:1.6.4    There is no corresponding document reference
To solve all the problems you encounter?

**Comment by vivekshindhe** [comment]
@317056658 its a continuous WIP. Will be updated soon. Hope this solved your issue?

**Comment by 317056658** [comment]
@vivekshindhe   thank you

**Comment by 317056658** [comment]
@vivekshindhe   Android studio prompt: ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@816cd5 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@816cd5 that was originally registered here. Are you missing a call to unregisterReceiver()?

add code  json.put("send_sms_hash",true) ，  There are still bugs

**Comment by goswamiji0** [comment]
I'm also facing the same issue 
 Android studio prompt: ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@816cd5 that was originally registered here. Are you missing a call to unregisterReceiver()?
android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@816cd5 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by JagadeeshDamarasingu** [comment]
@vivekshindhe , @goswamiji0, @317056658 This issue still exists in 1.6.5

E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@f3190d3 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@f3190d3 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1594)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1374)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1614)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1580)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:681)
        at com.razorpay.CheckoutPresenterImpl$8.onFinish(CheckoutPresenterImpl.java:775)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by PembaTamang** [comment]
same issue here with the 1.6.5 sdk

**Comment by sumedht** [comment]
@317056658 @PembaTamang Looking into this. Probably we will release it in early next week

**Comment by sumedht** [comment]
@PembaTamang Fixed this in v1.6.7

**Comment by peeyushyogi** [comment]
Is this issue resolved 1.6.6.
what is solution for that

**Comment by sumedht** [comment]
@peeyushyogi Update ur SDK to latest version.

**Comment by Meenu1401** [comment]
@sumedht Still facing this issue with latest version 1.6.6
E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@d56cc96 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@d56cc96 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:640)
        at com.razorpay.CheckoutPresenterImpl$8.onFinish(CheckoutPresenterImpl.java:764)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7410)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by vivekshindhe** [comment]
@Meenu1401 This is not a fatal exception and is due to SMS_RETRIEVER_API for auto-read of OTP messages. This doesn't have any unintended side-effects before, during or after a payment transaction. We're looking into it, but you can stay assured this doesn't include any problems.

**Comment by anandnarayanrai** [comment]
E/com.razorpay.checkout: Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined
I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/payments/pay_HmfAzgl3Sf2Gma/callback/caf86e36924718b4c0b80530d2373cb2d27db986/rzp_test_5lPODXTLtApmqf?status=authorized&token_recurring_status=rejected&language_code=en (1)
E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@b27f659 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@b27f659 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1424)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1201)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1437)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
        at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:958)
        at com.razorpay.CheckoutBridge$10.secure(CheckoutBridge.java:158)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1243)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@cff37a3 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@cff37a3 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1424)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1201)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:636)
        at com.razorpay.CheckoutPresenterImpl$8.onFinish(CheckoutPresenterImpl.java:800)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by vivekshindhe** [comment]
@anandnarayanrai  this is not a fatal error. Please ignore.

**Comment by MohitBaghel** [comment]
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@b697dde that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@b697dde that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1429)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1210)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1437)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
        at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:828)
        at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:819)
        at com.razorpay.l__d$.secure(CheckoutBridge.java:27)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.z$_w$.run(CheckoutPresenterImpl.java:1243)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by vivekshindhe** [comment]
But sir, this is not a fatal error. In fact, this error is coming because of the SMS_RETREIVER_API from google. Nothing changes because of this. We are looking to resolve this once and for all. Please wait for the fix for this in the next version. Since this isn't a blocker this will be taken with P2 priority and be released with time. Thank you. @MohitBaghel
