### ISSUE TITLE
Android app crashing with following crash log

### ISSUE THREAD

**Issue by TejendraPX** [razorpay/razorpay-android-sample-app#219]
Binary XML file line #1 in package:layout/rzp_loader: Error inflating class x

Caused by java.lang.ClassNotFoundException: android.view.x
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:454)
       at android.view.LayoutInflater.createView(LayoutInflater.java:813)
       at android.view.LayoutInflater.createView(LayoutInflater.java:774)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:911)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:68)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:541)
       at android.app.Dialog.setContentView(Dialog.java:858)
       at com.razorpay.CheckoutUtils.showLoader(CheckoutUtils.java:306)
       at com.razorpay.CheckoutPresenterImpl.onPageStarted(CheckoutPresenterImpl.java:503)
       at com.razorpay.OtpElfCheckoutPresenterImpl.onPageStarted(OtpElfCheckoutPresenterImpl.java:77)
       at com.razorpay.PrimaryWebViewClient.onPageStarted(PrimaryWebViewClient.java:29)
       at hk.c(hk.java:2)
       at oL.handleMessage(oL.java:162)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by sumedht** [comment]
@TejendraPX As it's not strightly reproducible, we will need more details like version of the app version, device, OS

**Comment by TejendraPX** [comment]
@sumedht 
Version - 1.6.6
Device - Samsung m31s, Xiomi - Redmi Note4
OS - Android 11,10,7

**Comment by sumedht** [comment]
@TejendraPX r u still facing the same issue?

**Comment by TejendraPX** [comment]
This issue has been fixed for me.
