### ISSUE TITLE
I am getting this in crashlytics using native android sdk.Many crash happening in the production account

### ISSUE THREAD

**Issue by rameshsambu-dev** [razorpay/razorpay-android-sample-app#236]
`Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=(has extras) } in com.razorpay.AutoReadOtpHelper@5fbb266
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by rameshsambu-dev** [comment]
using the sdk  version implementation 'com.razorpay:checkout:1.6.5'

**Comment by rameshsambu-dev** [comment]
Caused by java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:203)
       at com.razorpay.AutoReadOtpHelper.onReceive(AutoReadOtpHelper.java:36)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by vivekshindhe** [comment]
@rameshsambu-dev Hey, we apologise for the late response, please update to v1.6.10 for this. This has been solved in that version. Thank you. Closing the ticket. Please open another ticket in case the issue persists.
