### ISSUE TITLE
PaymentResultWithDataListener PaymentData is returning null on failure case

### ISSUE THREAD

**Issue by mayank2212** [razorpay/razorpay-android-sample-app#240]
## Razorpay SDK Version :
 implementation 'com.razorpay:checkout:1.6.7'. 

### What you did:
We have implemented PaymentResultWithDataListener, when testing gateway response in TestMode, the Success case is working fine and we are getting all the data in PaymentData object. But in case of onPaymentError, the data object of PaymentData is always null. We need paymentData.getOrderId() to return the order id. But PaymentData is always null. 

## Code example, screenshot, or link to a repository:
we are getting these logs in our logcat as well 

E/com.razorpay.checkout: Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function

2021-06-17 14:20:06.191 29944-29944/com.xxxx.xxxxx I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/gateway/mocksharp/payment?key_id=rzp_test_rY0vOBNRFJeB5T (1)
2021

**Comment by vivekshindhe** [comment]
@mayank2212 Please update to 1.6.10.

**Comment by mayank2212** [comment]
@vivekshindhe Already tried, getting this error in 1.6.10 

`2021-06-17 16:02:29.600 8724-8724/com.xxxx.xxxx E/com.razorpay.checkout: Webview JS Error: Uncaught ReferenceError: otpPermissionCallback is not defined
2021-06-17 16:02:29.600 8724-8724/com.xxxx.xxxx  I/chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: otpPermissionCallback is not defined", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android&error={%22code%22:%22BAD_REQUEST_ERROR%22,%22description%22:%22Payment%20failed%22,%22source%22:%22issuer%22,%22step%22:%22payment_authorization%22,%22reason%22:%22payment_failed%22,%22metadata%22:{%22payment_id%22:%22pay_HO5w2SRBeLM6Hx%22,%22order_id%22:%22order_HO5vs97z7Z8GLj%22}} (1)
2021-06-17 16:02:29.605 8724-8777/com.xxxx.xxxx  D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 5 2
2021-06-17 16:02:29.606 8724-8724/com.xxxx.xxxx  E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@1aded99 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@1aded99 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:640)
        at com.razorpay.CheckoutPresenterImpl$8.onFinish(CheckoutPresenterImpl.java:800)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-06-17 16:02:29.964 8724-8724/com.xxxx.xxxx  D/com.razorpay.checkout: API Cancel hit: {"error":{"code":"BAD_REQUEST_ERROR","description":"Payment failed","source":"issuer","step":"payment_authorization","reason":"payment_failed","metadata":{"payment_id":"pay_HO5w2SRBeLM6Hx","order_id":"order_HO5vs97z7Z8GLj"}}}
2021-06-17 16:02:34.479 8724-8779/com.xxxx.xxxx  V/FA: Inactivity, disconnecting from the service
`

**Comment by vivekshindhe** [comment]
@mayank2212 Request you to go through the document thoroughly. Neither PaymentResultListener or PaymentResultWithDataListener returns PaymentData object in onPaymentError(int code, String error). This error response is as below, which I picked from the logs you shared above.

```
 {"error":{"code":"BAD_REQUEST_ERROR","description":"Payment 
 failed","source":"issuer","step":"payment_authorization","reason":"payment_failed","metadata":{"payment_id":"pay_HO5w2SRBeLM6Hx","order_id":"order_HO5vs97z7Z8GLj"}}}
```

Also, the logs you shared are generic logs. These aren't a Fatal Exception so you can safely ignore these.
