### ISSUE TITLE
Observe on crash after successful payment callback

### ISSUE THREAD

**Issue by Goutam-Kumar** [razorpay/razorpay-android-sample-app#241]
E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@ee7a061 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@ee7a061 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1476)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
        at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:922)
        at com.razorpay.CheckoutBridge$10.secure(CheckoutBridge.java:157)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1221)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.CheckoutPresenterImpl$17.run(CheckoutPresenterImpl.java:1207)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Goutam-Kumar** [comment]
I am getting above error after payment successful.

**Comment by vivekshindhe** [comment]
@Goutam-Kumar this is not a fatal exception. If the app is crashing, you should see logs after the line 
"Fatal Exception".

**Comment by vivekshindhe** [comment]
@Goutam-Kumar closing this due to inactivity. Please comment on this thread to reopen the issue or create another ticket in case any other issues. Thank you.
