### ISSUE TITLE
java.lang.NoSuchFieldError in CheckoutActivity

### ISSUE THREAD

**Issue by TheDukerChip** [razorpay/razorpay-android-sample-app#247]
## Description
When the Checkout screen opened the app is getting crashed

## Razorpay SDK Version :
1.6.6 

## Android OS Version :
8.1.0 (Nexus 5x)

## Stacktrace
Fatal Exception: java.lang.NoSuchFieldError: No static field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in /data/app/com.cricket.sportsindex-MsTMxa2nuP90JyOeSEKwqA==/base.apk!classes2.dex)
       at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:174)
       at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:103)
       at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
       at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by vivekshindhe** [comment]
@TheDukerChip please use version 1.6.10. Its the latest one. And has this issue resolved.

**Comment by TheDukerChip** [comment]
@vivekshindhe Thanks for that! Can you point me to the release notes?

**Comment by vivekshindhe** [comment]
The release notes are in the main docs as well. You can refer those from there. @TheDukerChip

**Comment by TheDukerChip** [comment]
@vivekshindhe I can't find any release notes for **1.6.10** here https://razorpay.com/docs/payment-gateway/android-integration/standard/#list-of-razorpay-android-standard-sdk-versions-last

**Comment by vivekshindhe** [comment]
@TheDukerChip thanks for pointing that out. It must not have been updated yet. Will work on that. In the mean while you can use v1.6.10. It didn't have any additional features. Just some bug fixes. Once the release notes are live will update you again.

**Comment by vsp0393** [comment]
I am using razorpay sdk for payment gateway in android and my most of the users getting two errors mentioned below  i am already using latest sdk version from razorpay documentation 'com.razorpay:checkout:1.6.36'

1 . Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.calvarytemple/com.razorpay.CheckoutActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

2. Fatal Exception: java.lang.NoSuchFieldError
No static field activity_result_invalid_parameters of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in base.apk!classes2.dex)
