### ISSUE TITLE
Activity not found com.razorpay.CheckoutActivity, declared in manifest?

### ISSUE THREAD

**Issue by Naresh-Katta** [razorpay/razorpay-android-sample-app#25]
When I tried to use the manifest demo,
I got to following error.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{myapp.myapp/myapp.myapp.activities.RazorPayActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {myapp.myapp/com.razorpay.CheckoutActivity}; have you declared this activity in your AndroidManifest.xml?
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3163)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3273)
       at android.app.ActivityThread.access$1000(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6959)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by android.content.ActivityNotFoundException: Unable to find explicit activity class {myapp.myapp/com.razorpay.CheckoutActivity}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1837)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1661)
       at android.app.Activity.startActivityFromFragment(Activity.java:4729)
       at android.app.Fragment.startActivityForResult(Fragment.java:1114)
       at android.app.Fragment.startActivityForResult(Fragment.java:1098)
       at com.razorpay.Checkout.onCreate(Unknown Source:143)
       at android.app.Fragment.performCreate(Fragment.java:2075)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:869)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
       at android.app.BackStackRecord.run(BackStackRecord.java:834)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1470)
       at android.app.Activity.performStart(Activity.java:6646)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3126)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3273)
       at android.app.ActivityThread.access$1000(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6959)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

[Log2.txt](https://github.com/razorpay/razorpay-android-sample-app/files/894228/Log2.txt)

Device I used for testing is Samsung J Max tab.
OS: 5.1.1

**Comment by hariramsvnit** [comment]
Hi Naresh,

Which version of SDK you have integrated?

**Comment by Naresh-Katta** [comment]
com.razorpay:checkout:1.2.0
which is in the read me of this repo.

**Comment by hariramsvnit** [comment]
This issue is unexpected, please provide integration code you have written for Razorpay SDK integration to  support@razorpay.com.

**Comment by Naresh-Katta** [comment]
> RazorPayActivity.java

     public class RazorPayActivity extends AppCompatActivity implements PaymentResultListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        startPayment();
    }

    @Override
    public void onPaymentSuccess(String razorpayPaymentID) {
        Intent intent = new Intent();
        //Toast.makeText(this, "Payment created successfully", Toast.LENGTH_LONG).show();
        intent.putExtra("razorpayPaymentID", razorpayPaymentID);
        setResult(RESULT_OK, intent);
        finish();
    }

    @Override
    public void onPaymentError(int error_code, String response) {
        setResult(RESULT_CANCELED);
        Toast.makeText(this, "Transaction Cancelled/Failed", Toast.LENGTH_LONG).show();
        finish();
    }

    public void startPayment() {
        Checkout checkout = new Checkout();
        final Activity activity = this;
        double amountD = getIntent().getDoubleExtra("amount", 0);
        String description = getIntent().getStringExtra("description");
        int amount = (int) (amountD * 100);
        try {
            JSONObject preFill = new JSONObject()
                    .put("email", getIntent().getStringExtra("email"))
                    .put("contact", getIntent().getStringExtra("contact"));

            JSONObject options = new JSONObject()
                    .put("name", "MyAppName")
                    .put("description", description)
                    .put("currency", "INR")
                    .put("amount", amount + "")// 5.00 rupees.
                    .put("prefill", preFill);
            checkout.open(activity, options);
        } catch (JSONException e) {
        }
    }

`AndroidManifest.xml`

        <meta-data
            android:name="com.razorpay.ApiKey"
            android:value="@string/razor_pay_key" />
        <activity
            android:name=".activities.RazorPayActivity"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateHidden|adjustResize" />

`app/build.graddle`

    //Razorpay
    compile 'com.razorpay:checkout:1.2.0'

This is the code I used for this.
The same code worked well with my Moto-G Turbo.

**Comment by hariramsvnit** [comment]
Oh, Is this issue device specific? Maybe you can clean the project, rebuild and check again on Samsung J Max tab.

**Comment by Naresh-Katta** [comment]
May be, I have no more devices to test :(

**Comment by hariramsvnit** [comment]
Okay, just clean the project and check again on Samsung J Max tab. If you still face the issue then clone this sample project and try to run it on Samsung J Max tab. Let me know the result of this, I will look into it.

**Comment by Naresh-Katta** [comment]
I really don't know whats happening here, but clone is working fine, but my code, even after clean project,  not working. :(

**Comment by hariramsvnit** [comment]
Okay, Can you please share manifest file code and also which Gradle plugin you are using?

**Comment by steelrooter** [comment]
@hariramsvnit Please close this if this issue was resolved on support.

**Comment by iAmAndroidDeveloper** [comment]
https://api.razorpay.com/v1/payments/:id when pass id its shown error

{"error":{"code":"BAD_REQUEST_ERROR","description":"Please provide your api key for authentication purposes."}}

and every time display login screen , then how to get proper response JSON format?
