### ISSUE TITLE
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver 

### ISSUE THREAD

**Issue by abhinavsuthar** [razorpay/razorpay-android-sample-app#253]
## Description

If I use `PaymentResultListener` everything works as expected, but if I use `PaymentResultWithDataListener` then below non-fatal error occurs and `void onPaymentError(int var1, String var2, PaymentData var3);` never gets called

## Razorpay SDK Version :
1.6.12 

## Android OS Version :
Happening for all devices and OS

### What you did:

We upgraded our app's target SDK version to 30 from 28. Due to this `Unable to find explicit activity class {com.mega.app/com.razorpay.CheckoutActivity}` this error happened (v1.5.16). So I had to update the razorpay lib version to 1.6.12. 

### What happened:

android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@1bd5abf that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1607)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1378)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1624)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1590)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1578)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:679)
        at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:828)
        at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:819)
        at com.razorpay.l__d$.secure(CheckoutBridge.java:27)
        at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
        at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
        at com.razorpay.z$_w$.run(CheckoutPresenterImpl.java:1243)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
        
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Set TargetSDKVersion to 30
2. Use `PaymentResultWithDataListener` callbacks
3. Callbacks will not be called

### Suggested solution:
None 😭

## Code example, screenshot, or link to a repository:
Our code is exactly same as your's sample here - [Razorpay Android Sample App](https://github.com/razorpay/razorpay-android-sample-app/blob/master/app/src/main/java/com/razorpay/sampleapp/java/PaymentActivity.java)

**Comment by sumedht** [comment]
@abhinavsuthar Thanks for sharing the details. We will check with steps to reproduce & update here.

**Comment by vivekshindhe** [comment]
@abhinavsuthar This issue has been resolved in version 1.6.15. Please update to the same. Closing the ticket now. Please feel free to add another comment here or create another one in case of another query. Thank you.

**Comment by abhinavsuthar** [comment]
Thanks @vivekshindhe, will check and update here.
