### ISSUE TITLE
Unable to use External wallet in v1.6.12 

### ISSUE THREAD

**Issue by somesh-basicx** [razorpay/razorpay-android-sample-app#254]
## Description
After upgrading from com.razorpay:checkout:1.5.14, we are unable to use external wallet like Paytm. Previously we used to define 'paytm' as an external wallet and get the callback on `onExternalWalletSelected()` method but in this new SDK, we are getting "order_id" not set exception when selecting an external wallet. When I downgrade to v1.5.14, I am able to select Paytm wallet and get the callback in `onExternalWalletSelected` but get the below error trace when selecting it with the newer version. As a test, I added citrus wallet and got the same error in the newer version. Are there any changes to how we can get wallet selection callback for Paytm in the newer version? if yes I can't find the documentation. I am able to select all the default available wallets like Payzap or Freechage with both the SDK versions but not the external wallets; 

### What you did:
This is how I add Paytm and other wallets in the checkout object. 

```
 JSONArray wallets = new JSONArray();
 wallets.put("paytm");
 JSONObject externals = new JSONObject();
 externals.put("wallets", wallets);
 
options.put(external, externals);
```

### What happened:

This is the error trace I get after clicking Paytm wallet from the checkout page of Razorpay (some information replaced with _XXXX_):
```
W/System.err: java.lang.IllegalArgumentException: Receiver not registered: com.razorpay.AutoReadOtpHelper@8c77695
W/System.err:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1338)
W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1583)
W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:672)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:938)
W/System.err:     at com.razorpay.J$_0_.secure(CheckoutBridge.java:158)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
W/System.err:     at com.razorpay.z$_w$.run(CheckoutPresenterImpl.java:1243)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
W/System.err: org.json.JSONException: No value for order_id
W/System.err:     at org.json.JSONObject.get(JSONObject.java:392)
W/System.err:     at com.razorpay.D$$l_.a(Lumberjack.java:423)
W/System.err:     at com.razorpay.D$$l_.a(Lumberjack.java:407)
W/System.err:     at com.razorpay.D$$l_.a(Lumberjack.java:463)
W/System.err:     at com.razorpay.AnalyticsUtil.addFilteredPropertiesFromPayload(AnalyticsUtil.java:108)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.addAnalyticsData(CheckoutPresenterImpl.java:924)
W/System.err:     at com.razorpay.S__Z$.addAnalyticsData(OtpElfCheckoutPresenterImpl.java:171)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.onSubmit(CheckoutPresenterImpl.java:947)
W/System.err:     at com.razorpay.J$_0_.secure(CheckoutBridge.java:158)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
W/System.err:     at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
W/System.err:     at com.razorpay.z$_w$.run(CheckoutPresenterImpl.java:1243)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
D/com.razorpay.checkout: {"key":"NTZmNWIwNGZhODc1MmUyY2YxOTMXXXX","events":[{"event":"assist:and_error_log","timestamp":"1629796373","properties":{"error_message":"Receiver not registered: com.razorpay.AutoReadOtpHelper@8c77695","error_level":"error","local_order_id":"Gnxs3Pk6CLlFar","local_payment_id":"GnXX3PsUXXUhRm","merchant_app_name":"BASICX SPORT","merchant_app_version":"Development Build","merchant_app_build":51,"platform":"mobile_sdk","platform_version":"1.6.12","os":"android","os_version":"9","library":"CHECKOUTJS","wallet":"paytm","method":"wallet","payment_attempt":1,"amount":36400,"OTPElf Version":"MD5","contact":"+9177XXXXXX","merchant_package":"com.basicx.XXXXXX","merchant_key":"rzp_test_XXXXXXXX","merchant options":{"name":"BASICX SPORT","description":"Order # XXXXXX_1629796294553","order_id":"order_HoyXXXXXX","currency":"INR","amount":"36400","prefill.email":"somXXX@basicx.in","prefill.contact":"773XXXXXXX","retry":{"enabled":true,"max_count":4},"external":{"wallets":["paytm"]},"key":"rzp_test_XXXXXXXX","redirect":true,"prefill":{"email":"soXXXXX@basicx.in","contact":"+9177XXXXXXXX"}},"email":"soXXXXX@basicx.in"}},{"event":"assist:and_error_log","timestamp":"1629796373","properties":{"error_message":"No value for order_id","error_level":"warning","local_order_id":"Gnxs3Pk6CLlFar","local_payment_id":"Gnxs3PsUUPUhRm","merchant_app_name":"BASICX SPORT","merchant_app_version":"Development Build","merchant_app_build":51,"platform":"mobile_sdk","platform_version":"1.6.12","os":"android","os_version":"9","library":"CHECKOUTJS","wallet":"paytm","method":"wallet","payment_attempt":1,"amount":36400,"OTPElf Version":"MD5","contact":"+9177XXXXXX","merchant_package":"com.basicx.XXXXXX","merchant_key":"rzp_test_XXXXXXXX","merchant options":{"name":"BASICX SPORT","description":"Order # BX1446_1629796294553","order_id":"order_HoyXXXXXX","currency":"INR","amount":"36400","prefill.email":"soXXXXX@basicx.in","prefill.contact":"9177XXXXXX","retry":{"enabled":true,"max_count":4},"external":{"wallets":["paytm"]},"key":"rzp_test_XXXXXXXX","redirect":true,"prefill":{"email":"soXXXXX@basicx.in","contact":"+9177XXXXXX"}},"email":"soXXXXX@basicx.in"}},{"event":"ch:and_checkout_submit","timestamp":"1629796373","properties":{"local_order_id":"Gnxs3PXXXLlFar","local_payment_id":"Gnxs3XXXUPUhRm","merchant_app_name":"BASICX SPORT","merchant_app_version":"Development Build","merchant_app_build":51,"platform":"mobile_sdk","platform_version":"1.6.12","os":"android","os_version":"9","library":"CHECKOUTJS","wallet":"paytm","method":"wallet","payment_attempt":1,"amount":36400,"OTPElf Version":"MD5","contact":"+9177XXXXXX","merchant_package":"com.basicx.XXXXXX","merchant_key":"rzp_test_XXXXXXXX","merchant options":{"name":"BASICX SPORT","description":"Order # BX1446_1629796294553","order_id":"order_HoyXXXXXX","currency":"INR","amount":"36400","prefill.email":"soXXXXX@basicx.in","prefill.contact":"9177XXXXXX","retry":{"enabled":true,"max_count":4},"external":{"wallets":["paytm"]},"key":"rzp_test_XXXXXXXX","redirect":true,"prefill":{"email":"soXXXXX@basicx.in","contact":"+9177XXXXXX"}},"email":"soXXXXX@basicx.in"}}],"context":{"mode":"test","device":{"id":"53c50228-ead6-44f7-89d8-2b260efc12a5","manufacturer":"samsung","model":"SM-G950F","name":"dreamlte","type":"phone","version":"Android9","samsung":"samsung","SM-G950F":"SM-G950F","device_size":"1440w X 2768h","device_resolution":"1440x2768x640"},"sdk":{"version":"1.6.12","type":"checkout"},"network":{"bluetooth":false,"carrier":"Jio 4G","cellular":true,"cellular_network_type":"4G","wifi":false,"carrier_network":"Jio 4G","network_type":4,"is_roming":false},"screen":{"density":4,"width":1440,"height":2768},"locale":"en-GB","timezone":"Asia\/Kolkata","user_agent":"Dalvik\/2.1.0 (Linux; U; Android 9; SM-G950F Build\/PPR1.180610.011)","webview_user_agent":"Mozilla\/5.0 (Linux; Android 9; SM-G950F Build\/PPR1.180610.011; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/92.0.4515.131 Mobile Safari\/537.
D/com.razorpay.checkout: Sending data to lumberjack
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. User version 1.6.12 of Razorpay SDK
2. Add external wallets like Paytm
3. Select wallets > Paytm at checkout 
4. Boom you get the error

### Suggested solution:
Nothing

**Comment by somesh-basicx** [comment]
_**Bump!**_

**Comment by somesh-basicx** [comment]
@sumedht Anything on this? If this is a real issue then this should be a critical one!

**Comment by sumedht** [comment]
@somesh-basicx We have fixed this issue now & will release it on 30th Sep with the new version of SDK 1.6.13

**Comment by vivekshindhe** [comment]
@somesh-basicx The issue has been resolved. Please use the version 1.6.15 for the same. Thank you for your patience. Closing the ticket now.
