### ISSUE TITLE
It is working fine in debug mode. But in release ver only the art screen is open and the phone hangs.

### ISSUE THREAD

**Issue by sahujaunpuri** [razorpay/razorpay-android-sample-app#257]
## Description

It is working fine in debug mode. But in release ver only the art screen is open and the phone hangs.
when i am using live key
## Razorpay SDK Version :
com.razorpay:checkout:1.6.10. 

### What you did:
          `                    public void CreateOrderId(String payble) {
               Map<String, String> params = new HashMap<>();
                 params.put("amount", "" + Math.round(Float.parseFloat(payble)) + "00");
               ApiConfig.RequestToVolley(new VolleyCallback() {
                   @Override
                 public void onSuccess(boolean result, String response) {
                if (result) {
                    try {
                        JSONObject object = new JSONObject(response);
                        if (!object.getBoolean(Constant.ERROR)) {
                            startPayment(object.getString("id"), object.getString("amount"));
                            System.out.println("Get_RazorPay_OrderId" + params.toString()  );
                        }
                    } catch (JSONException e) {
                        System.out.println("Get_RazorPay_OrderId JSONException" + e .toString()  );
                    }
                }
                 }
                }, ServiceCheckoutActivity.this, Constant.Get_RazorPay_OrderId, params, true);
                }
          public void startPayment(String orderId, String payAmount) {
          final Activity activity = this;
        final Checkout co = new Checkout();
        co.setImage(R.drawable.ic_logo);
        try {
            JSONObject options = new JSONObject();
            System.out.println("Get_RazorPay startPayment" + options  );
            options.put(Constant.NAME, session.getData(Constant.NAME));
            if (from.equalsIgnoreCase("LpgBookingActivity")) {
                options.put("description", "For Lpg Booking");
            }else if (from.equalsIgnoreCase("ElectricalServices")) {
                options.put("description", "For Electricaity Bill");
            }
            options.put("send_sms_hash",true);
            options.put("image", "https://xy/dist/img/logo.png");
            options.put(Constant.ORDER_ID, orderId);
            options.put(Constant.CURRENCY, "INR");
            options.put(Constant.AMOUNT, payAmount);
            JSONObject preFill = new JSONObject();
            System.out.println("Get_RazorPay startPayment preFill" + preFill  );
            preFill.put(Constant.EMAIL, session.getData(Constant.EMAIL));
            preFill.put(Constant.CONTACT, session.getData(Constant.MOBILE));
            options.put("prefill", preFill);
             co.open(activity, options);
        } catch (Exception e) {
            Log.d(TAG, "Error in starting Razorpay Checkout", e);

        }
    }
    @Override
    public void onPaymentSuccess(String razorpayPaymentID) {
        try {
            razorPayId = razorpayPaymentID;
            razorParams.put(Constant.ORDER_ID, razorPayId);
          /*  PlaceOrder(paymentMethod, razorPayId, true, razorParams, "Success");*/
            if (from.equalsIgnoreCase("LpgBookingActivity")) {
                PlaceLPGOrder(paymentMethod, razorPayId, true, razorParams, "Success");
            }else if (from.equalsIgnoreCase("ElectricalServices")) {
                PlaceOrder(paymentMethod, razorPayId, true, razorParams, "Success");
            }
        } catch (Exception e) {
            Log.d(TAG, "onPaymentSuccess  ", e);
        }
    }

        @Override
        public void onPaymentError(int code, String response) {
        try {
            Toast.makeText(this, response, Toast.LENGTH_LONG).show();
            System.out.println("onPaymentError = " + response + "/ code /" + code);
        } catch (Exception e) {
            Log.d(TAG, "onPaymentError  ", e);
        }
    }`

### What happened:

It is working fine in debug mode. But in release ver only the art screen is open and the phone hangs.
when i am using live key

![Screenshot_20210909-225033_Henkako Plus Shop](https://user-images.githubusercontent.com/22550065/132732904-23340dbc-b9fc-4123-84bd-db90b8d59551.jpg)

**Comment by vivekshindhe** [comment]
Please ensure you have added the correct proguard rules.

**Comment by sahujaunpuri** [comment]
> Please ensure you have added the correct proguard rules.

    `-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
     }
     -keepattributes JavascriptInterface
    -keepattributes *Annotation*
    -dontwarn com.razorpay.**
    -keep class com.razorpay.** {*;}
    -optimizations !method/inlining/*
     -keepclasseswithmembers class * {
     public void onPayment*(...);
     }`

**Comment by vivekshindhe** [comment]
@sahujaunpuri can you enable logging and check if you are getting some logs there? We'll be able to identify the issue and resolve it sooner that way.

**Comment by sahujaunpuri** [comment]
> enable



> @sahujaunpuri can you **enable logging** and check if you are getting some logs there? We'll be able to identify the issue and resolve it sooner that way.

Sir how will logging be enabled in release ver? give some guidance please

**Comment by vivekshindhe** [comment]
@sahujaunpuri Sirji, in build.gradle you should find the build variant release. In that, you can type 
`debuggable true`. 
This should enable logging even in release mode.

**Comment by sahujaunpuri** [comment]
`buildTypes {
        debug {
            minifyEnabled false
            debuggable true
        }
        release {
            minifyEnabled true
            debuggable false
            proguardFile 'proguard-project.txt'
        }
        }`

**Comment by vivekshindhe** [comment]
@sahujaunpuri Yes

**Comment by sahujaunpuri** [comment]
> @sahujaunpuri can you enable logging and check if you are getting some logs there? We'll be able to identify the issue and resolve it sooner that way.

Logs are as

> 2021-09-20 22:52:47.689 30861-30861/my-package-name W/System.err: java.lang.IllegalArgumentException: bad base-64
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at android.util.Base64.decode(Base64.java:163)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at android.util.Base64.decode(Base64.java:138)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at com.razorpay.v.d(SourceFile:174)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at com.razorpay.v.b(SourceFile:269)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at com.razorpay.i.e(SourceFile:719)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at com.razorpay.E$b.a(SourceFile:55)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at com.razorpay.F.g(SourceFile:137)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at com.razorpay.F.onPostExecute(SourceFile:23)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:771)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask.access$900(AsyncTask.java:199)
2021-09-20 22:52:47.696 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
2021-09-20 22:52:47.697 30861-30861/my-package-name W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-09-20 22:52:47.697 30861-30861/my-package-name W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-09-20 22:52:47.697 30861-30861/my-package-name W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8577)
2021-09-20 22:52:47.697 30861-30861/my-package-name W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-09-20 22:52:47.697 30861-30861/my-package-name W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-09-20 22:52:47.697 30861-30861/my-package-name W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-09-20 22:52:47.697 30861-30861/my-package-name D/com.razorpay.checkout: Unable to decrypt file, bad base-64
2021-09-20 22:52:47.759 30861-30861/my-package-name W/System.err: java.lang.IllegalArgumentException: bad base-64
2021-09-20 22:52:47.759 30861-30861/my-package-name W/System.err:     at android.util.Base64.decode(Base64.java:163)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.util.Base64.decode(Base64.java:138)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at com.razorpay.v.d(SourceFile:174)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at com.razorpay.v.b(SourceFile:269)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at com.razorpay.i.e(SourceFile:719)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at com.razorpay.E$b.a(SourceFile:55)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at com.razorpay.F.g(SourceFile:137)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at com.razorpay.F.onPostExecute(SourceFile:23)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:771)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask.access$900(AsyncTask.java:199)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-09-20 22:52:47.760 30861-30861/my-package-name W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8577)
2021-09-20 22:52:47.761 30861-30861/my-package-name W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-09-20 22:52:47.761 30861-30861/my-package-name W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-09-20 22:52:47.761 30861-30861/my-package-name W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-09-20 22:52:47.761 30861-30861/my-package-name D/com.razorpay.checkout: Unable to decrypt file, bad base-64
2021-09-20 22:52:47.819 30861-30861/my-package-name W/System.err: java.lang.IllegalArgumentException: bad base-64
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.util.Base64.decode(Base64.java:163)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.util.Base64.decode(Base64.java:138)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at com.razorpay.v.d(SourceFile:174)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at com.razorpay.v.b(SourceFile:269)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at com.razorpay.i.e(SourceFile:719)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at com.razorpay.B$b.a(SourceFile:41)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at com.razorpay.F.g(SourceFile:137)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at com.razorpay.F.onPostExecute(SourceFile:23)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:771)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask.access$900(AsyncTask.java:199)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-09-20 22:52:47.820 30861-30861/my-package-name W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-09-20 22:52:47.821 30861-30861/my-package-name W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8577)
2021-09-20 22:52:47.821 30861-30861/my-package-name W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-09-20 22:52:47.821 30861-30861/my-package-name W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-09-20 22:52:47.821 30861-30861/my-package-name W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-09-20 22:52:47.821 30861-30861/my-package-name D/com.razorpay.checkout: Unable to decrypt file, bad base-64
2021-09-20 22:52:48.949 30861-30861/my-package-name I/ViewRootImpl@67e7871[CheckoutActivity]: dispatchDetachedFromWindow
2021-09-20 22:52:48.949 30861-30861/my-package-name I/SurfaceControl: nativeRelease nativeObject s[484856657152]
2021-09-20 22:52:48.950 30861-30861/my-package-name I/SurfaceControl: nativeRelease nativeObject e[484856657152]
2021-09-20 22:52:48.962 30861-30861/my-package-name D/InputTransport: Input channel destroyed: 'b4255f5', fd=187
2021-09-20 22:52:48.969 30861-30861/my-package-name D/com.razorpay.checkout: Checkout loaded in 3.83 sec.
2021-09-20 22:52:48.970 30861-31136/my-package-name I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-09-20 22:52:48.970 30861-31136/my-package-name I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-09-20 22:52:48.975 30861-30861/my-package-name D/com.razorpay.checkout: not magic
2021-09-20 22:52:49.034 30861-30861/my-package-name E/com.razorpay.checkout: Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
2021-09-20 22:52:49.037 30861-30861/my-package-name I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android (1)
2021-09-20 22:52:49.071 30861-30861/my-package-name E/com.razorpay.checkout: Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function
2021-09-20 22:52:49.071 30861-30861/my-package-name I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.10&library=checkoutjs&platform=android (1)

**Comment by vivekshindhe** [comment]
@sahujaunpuri Is this all of the logs? The error you are seeing Webview JS Error and Uncaught TypeError, these are not fatal. If there are more than that, would like to see it. Also, would like an apk to test it on our end. You can minify and shrink it. We just want to see this happening. If that is possible you can mail it to me(vivek.shindhe@razorpay.com).

**Comment by sahujaunpuri** [comment]
i has sent you

**Comment by vivekshindhe** [comment]
@sahujaunpuri Have replied you on that. Please look into it and confirm on the queries.
