### ISSUE TITLE
CheckoutActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by prabhuc94** [razorpay/razorpay-android-sample-app#265]
2021-10-17 20:23 E/ActivityThread: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@161e3f8 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@161e3f8 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1618)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1398)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1614)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1580)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:681)
        at com.razorpay.CheckoutPresenterImpl$16.onFinish(CheckoutPresenterImpl.java:805)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by vivekshindhe** [comment]
@prabhuc94 This has been resolved in version 1.6.15. Please update to this one. This was not an error. Just the receiver for SMS_RETREIVER_API. Hence would not block flow. Thank you.
