### ISSUE TITLE
java.lang.RuntimeException: Unable to destroy activity {app.debug/com.razorpay.CheckoutActivity}: java.lang.IllegalArgumentException: Receiver not registered: null

### ISSUE THREAD

**Issue by FireAndIce** [razorpay/razorpay-android-sample-app#266]
After a successful transaction using Razorpay, when the flow returns from the CheckoutActivity to the application's MainActivity, the following error is being encountered: 

`java.lang.RuntimeException: Unable to destroy activity {app.debug/com.razorpay.CheckoutActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5111)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1435)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1642)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:715)
        at com.razorpay.CheckoutPresenterImpl.cleanUpOnDestroy(CheckoutPresenterImpl.java:705)
        at com.razorpay.a_$P$.onDestroy(BaseCheckoutActivity.java:178)
        at android.app.Activity.performDestroy(Activity.java:8245)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by vivekshindhe** [comment]
@FireAndIce  this has been resolved in version 1.6.15. Please use that. Thank you for your patience. Closing the ticket
