### ISSUE TITLE
App crashed on this line **AdvertisingIdUtil.java line 47**  **com.razorpay.a_$P$.a**

### ISSUE THREAD

**Issue by lovepreetSinghElectricpe** [razorpay/razorpay-android-sample-app#290]
## Description

Hi, 
I am getting an error on this line **AdvertisingIdUtil.java line 47**  **com.razorpay.a_$P$.a**

Firebase Logs :
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:415)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalArgumentException: Service not registered: com.razorpay.G__G_@4645009
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1931)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1929)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:802)
       at com.razorpay.a_$P$.a(AdvertisingIdUtil.java:47)
       at com.razorpay.a_$P$.doInBackground(AdvertisingIdUtil.java:25)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

## Razorpay SDK Version :
com.razorpay:checkout:1.6.12

## Android OS Version :
Received crash from Realme-7(Android 11)

## Steps To Reproduce
Not exactly sure how to reproduce, but it looks like user moved the app to background while on razorpay checkout page.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
@lovepreetSinghElectricpe This has been taken care of in the latest version. Please update and let us know. Thank you

**Comment by lovepreetSinghElectricpe** [comment]
Looks like it has been solved with the update.
