### ISSUE TITLE
Facing - Fatal Exception: java.lang.ExceptionInInitializerError while initializing the Razor pay SDK

### ISSUE THREAD

**Issue by msoni-oyo** [razorpay/razorpay-android-sample-app#305]
## Description

Some of the user are getting "ExceptionInInitializerError" while making payment through our app. The instances of the crash are spotted on crashlytics. 

## Razorpay SDK Version :
Open `build.gradle`. >  razorpay-android-3.6.0.aar 

## Android OS Version : 
The issue is coming on 10, 11, 12

### What you did:

We have used the Razor pay sdk for making payment in our app. As we observe the crash reports on Fabric we found there are some of the crashes reported due to the razor pay SDK. 

### What happened:

Fatal Exception: java.lang.ExceptionInInitializerError
       at com.razorpay.g__v_.Q_$2$()
       at com.razorpay.E$_j$.a_$P$(SourceFile:182)
       at com.razorpay.l_$w$.d__1_(SourceFile:380)
       at com.razorpay.BaseRazorpay.R$$r_(SourceFile:124)
       at com.razorpay.BaseRazorpay.<init>(SourceFile:114)
       at com.razorpay.Razorpay.<init>(SourceFile:23)
       at com.oyo.consumer.payament.v2.utils.PaymentAttachUtilsKt.getEmptyAttachablePresenter(PaymentAttachUtils.kt:39)
       at com.oyo.consumer.hotel_v2.view.HotelDetailsActivity.ensurePayPresenter(HotelDetailsActivity.kt:61)
       at com.oyo.consumer.hotel_v2.view.HotelDetailsActivity.getPaymentPresenter(HotelDetailsActivity.kt:67)
       at com.oyo.consumer.hotel_v2.view.HotelDetailFragment$presenter$2.invoke(HotelDetailFragment.kt:81)
       at com.oyo.consumer.hotel_v2.view.HotelDetailFragment$presenter$2.invoke(HotelDetailFragment.kt:80)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.oyo.consumer.hotel_v2.view.HotelDetailFragment.getPresenter(HotelDetailFragment.kt:80)
       at com.oyo.consumer.hotel_v2.view.HotelDetailFragment.onViewCreated(HotelDetailFragment.kt:662)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
       at com.oyo.consumer.activity.BaseActivity.onStart(BaseActivity.java:443)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8231)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3861)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

## Steps To Reproduce

There is no such steps we know to reproduce. 

### Suggested solution:

We need a proper solution to fixe it. 

## Code example, screenshot, or link to a repository:
 //in the following code the error is coming :
  var razorpay: Razorpay? = null
    // Razor pay is throwing crashes for some of the devices
    // so adding try catch until the crash is fixed from razor pay sdk
    try {
        razorpay = Razorpay(activity)
    } catch (e: Exception) {
        Logr.logException(e)
    }

**Comment by vivekshindhe** [comment]
@msoni-oyo 3.6.0 is wayy too old. Can you please update to 3.9.9? This has been moved to maven. And test with that once.

**Comment by msoni-oyo** [comment]
@vivekshindhe Thanks for an update let me use SDK version 3.9.9. Hope it is a stable version. 
If possible pls share a migration doc with me.

**Comment by msoni-oyo** [comment]
Can you pls share me the link to get the latest SDK?

**Comment by msoni-oyo** [comment]
@vivekshindhe  Can you pls share the link to .aar version 3.9.9

**Comment by vivekshindhe** [comment]
@msoni-oyo  we've changed the implementation to maven now. You can find it on maven now. https://razorpay.com/docs/payments/payment-gateway/android-integration/custom/

Doc link

**Comment by vivekshindhe** [comment]
Closing ticket due to inactivity. Hope the issue was resolved for you. Comment here to reopen or create another ticket for further queries. Thank you
