### ISSUE TITLE
NullPointerException in Checkout screen

### ISSUE THREAD

**Issue by umangce** [razorpay/razorpay-android-sample-app#33]
I opened Activity which contains `Checkout.preload(getApplicationContext());` and closed it immediately. Then app got crashed and found following exception from Crashlytics. Can you please look into this issue?

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.setTag(java.lang.Object)' on a null object reference
       at com.razorpay.Checkout$5.onPageStarted(Unknown Source:149)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:532)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:157)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)`

**Comment by AbhinavArora95** [comment]
@umangce - Can you please share a few details so that we can reproduce the error -

1. On which device were you running the application and which Android OS ?
2. Did you add an code of yours to the application ?
3. How did you close the app - by pressing the back button or force close ?

Any other details so that we can reproduce the error would be really helpful.

**Comment by umangce** [comment]
1. Moto G5 Plus which runs on Android Nougat 7.0
2. Yes
3. Closed that screen by pressing back button

**Comment by AbhinavArora95** [comment]
@umangce - could you please share the details of the code that was added by you ?

**Comment by umangce** [comment]
I have added `Checkout.preload(getApplicationContext())` in `onCreate()` as per your guidelines. Rest of code in that Activity was my app's logic, nothing fancy. And that code doesn't impact on payment related code.

**Comment by AbhinavArora95** [comment]
@umagce - thanks for your help. We have solved the issue and will be updating the sample app soon.

**Comment by hariramsvnit** [comment]
@umangce We have fixed the crash in [v1.3.4](https://github.com/razorpay/razorpay-android-sample-app/releases/tag/v1.3.4)

**Comment by umangce** [comment]
Thank You!
