### ISSUE TITLE
Error :- java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;	at com.razorpay.OpinionatedSoln.getBuildConfigValue(Unknown Source:2)	at com.razorpay.Checkout.open(Checkout.java:141)

### ISSUE THREAD

**Issue by AGCcreato** [razorpay/razorpay-android-sample-app#334]
Plz Help on this crashing error while clicking on Pay Button

Error :- java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;	at com.razorpay.OpinionatedSoln.getBuildConfigValue(Unknown Source:2)	at com.razorpay.Checkout.open(Checkout.java:141)

Full Error - java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at com.razorpay.OpinionatedSoln.getBuildConfigValue(Unknown Source:2)
	at com.razorpay.Checkout.open(Checkout.java:141)
	at demo.razorpay.agc.MainActivity._StartPayment(MainActivity.java:185)
	at demo.razorpay.agc.MainActivity$2.onClick(MainActivity.java:95)
	at android.view.View.performClick(View.java:7870)
	at android.widget.TextView.performClick(TextView.java:14966)
	at android.view.View.performClickInternal(View.java:7839)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29363)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	... 16 more

**Comment by vivekshindhe** [comment]
@AGCcreato which version are you using?

**Comment by AGCcreato** [comment]
> @AGCcreato which version are you using?

v.1.6.26

**Comment by vivekshindhe** [comment]
this is an error regarding the Kotlin version being used. Something that has to do with sourceCompatibility & jvmTarget. 
You can add this line to your build.gradle file and it should start working,
`    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10'`

1.7.10 is the kotlin version of my project. Please replace that with the version of Kotlin being used by gradle.

**Comment by AGCcreato** [comment]
> this is an error regarding the Kotlin version being used. Something that has to do with sourceCompatibility & jvmTarget. You can add this line to your build.gradle file and it should start working, ` implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10'`
> 
> 1.7.10 is the kotlin version of my project. Please replace that with the version of Kotlin being used by gradle.

Thankyou, it works in Android studio 

But If you know about Sketchware Pro it not supporting razorpay v.1.6.26 but it's supporting v1.6.6.

Sketchware Pro is unable to add org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10 this library in it 

So I need add it manually in native libarary or making my it's a new supporting library in Sketchware pro a Android IDE for Android Phones

Thankyou
