### ISSUE TITLE
Binary XML file line #22 in com.example:layout/sdk_integration_status: Binary XML file line #22 in com.example:layout/sdk_integration_status: Error inflating class android.widget.ListView

### ISSUE THREAD

**Issue by alpeshshiyal** [razorpay/razorpay-android-sample-app#335]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 11614
    android.view.InflateException: Binary XML file line #22 in com.example:layout/sdk_integration_status: Binary XML file line #22 in com.example:layout/sdk_integration_status: Error inflating class android.widget.ListView
    Caused by: android.view.InflateException: Binary XML file line #22 in com.example:layout/sdk_integration_status: Error inflating class android.widget.ListView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createView(LayoutInflater.java:780)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at com.razorpay.OpinionatedSoln.showDialog(OpinionatedSoln.kt:103)
        at com.razorpay.OpinionatedSoln.checkEnvVariablesForProject(OpinionatedSoln.kt:50)
        at com.razorpay.OpinionatedSoln.checkIfVersionUpdateExists$lambda-0(OpinionatedSoln.kt:90)
        at com.razorpay.OpinionatedSoln.lambda$ituiA8PJbUra1G6hD5zylJQ_zic(Unknown Source:0)
        at com.razorpay.-$$Lambda$OpinionatedSoln$ituiA8PJbUra1G6hD5zylJQ_zic.run(Unknown Source:4)
        at com.razorpay.M$_3_.onPostExecute(Owl.java:5137)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.main
     
     Using following version :
       implementation 'com.razorpay:checkout:1.6.26'

**Comment by vivekshindhe** [comment]
@alpeshshiyal Is this a sample app? Is there a repo I can use to test this out?

**Comment by alpeshshiyal** [comment]
> Contributor

Not yet , this is in live project
