### ISSUE TITLE
UPI payments stopped working in a new app build

### ISSUE THREAD

**Issue by Rutulpatel7077** [razorpay/razorpay-android-sample-app#344]
## Description

Hey Razorpay team,

We are currently having issues with UPI payments. Our mobile app is live on the play store where we have operational Razorpay integrated and it's working well.  

We made a few updates in the app ( other changes ), and now the new build has a UPI payment error. We have not changed anything in the code related to Razorpay. Other payment methods are working so we think something is wrong with Razorpay.

We keep getting errors saying: "Invalid VPA".

We reached out to support and they are saying it's because have not added the app URL in the dashboard and some UPI terminal is missing.  It's kind of confusing when they say that because the app is live for the last 1.5 years and we were making constant updates to it without issues. 

I just want to check here if there is anything else causing this issue? 

## Razorpay SDK Version : 
`com.razorpay:checkout:1.6.12`

## Android OS Version :
We are having issues with app versions of android.

### What you did:
We made other UI and features related changes in the app.

### What happened:
UPI payments stopped working.
Here are some logs we are getting, but not sure if it's related to the UPI payments.

java.lang.SecurityException: getDataNetworkTypeForSubscriber
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Parcel.createException(Parcel.java:3007)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Parcel.readException(Parcel.java:2990)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Parcel.readException(Parcel.java:2932)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8593)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3677)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3641)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.BaseUtils.getCellularNetworkType(BaseUtils.java:344)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.BaseUtils.getNetworkType(BaseUtils.java:325)
2023-03-10 17:05:50.600 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.getOptionsForHandleMessage(CheckoutPresenterImpl.java:855)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.getHandleMessageFormattedString(CheckoutPresenterImpl.java:866)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.access$300(CheckoutPresenterImpl.java:49)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.d__w$.run(CheckoutPresenterImpl.java:778)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at android.app.Activity.runOnUiThread(Activity.java:7489)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:775)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.l__d$.secure(CheckoutBridge.java:27)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1257)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:49)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.z$_w$.run(CheckoutPresenterImpl.java:1243)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Handler.handleCallback(Handler.java:942)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2023-03-10 17:05:50.601 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)

===========================================================

javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2056)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CryptLib.a(CryptLib.java:176)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CryptLib.b(CryptLib.java:269)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:750)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.BaseUtils.getFileFromInternal(BaseUtils.java:742)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.OtpElfData.getOtpElfJs(OtpElfData.java:76)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.RzpAssist.handleJsInsertion(RzpAssist.java:160)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.RzpAssist.onPageFinished(RzpAssist.java:125)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.S__Z$.primaryWebviewPageFinished(OtpElfCheckoutPresenterImpl.java:115)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.CheckoutPresenterImpl.onPageFinished(CheckoutPresenterImpl.java:554)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.S__Z$.onPageFinished(OtpElfCheckoutPresenterImpl.java:97)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at com.razorpay.PrimaryWebViewClient.onPageFinished(PrimaryWebViewClient.java:33)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at jA0.a(chromium-TrichromeWebViewGoogle.aab-beta-556305843:11)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at ya.handleMessage(chromium-TrichromeWebViewGoogle.aab-beta-556305843:328)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at android.os.Looper.loop(Looper.java:313)
2023-03-10 17:05:50.683 17482-17482/com.bhadegadi.partners W/System.err:     at android.app.Act

===========================================================

2023-03-10 17:05:50.681 17482-17482/com.bhadegadi.partners W/System.err: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

## Code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/22271244/225157548-2ab8e10a-1e50-430f-9c33-df9b0b84201b.png)

**Comment by Rutulpatel7077** [comment]
Looks like the issue with actual UPI Id
