### ISSUE TITLE
  Activity com.razorpay.CheckoutActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by xclusive43** [razorpay/razorpay-android-sample-app#349]
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@a071c95 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                         android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@a071c95 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                         	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1671)
                                         	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1401)
                                         	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1639)
                                         	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1605)
                                         	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1593)
                                         	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:668)
                                         	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:916)
                                         	at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:907)
                                         	at com.razorpay.J$_0_.secure(CheckoutBridge.java:27)
                                         	at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1370)
                                         	at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:55)
                                         	at com.razorpay.b$_f_.run(CheckoutPresenterImpl.java:1355)
                                         	at android.os.Handler.handleCallback(Handler.java:938)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at android.os.Looper.loop(Looper.java:257)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8218)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by xclusive43** [comment]
please provide the necessary solution for this

**Comment by riyazpara** [comment]
Same issue 

Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@2a67fad that was originally registered here. Are you missing a call to unregisterReceiver()?
             android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.AutoReadOtpHelper@2a67fad that was originally registered here. Are you missing a call to unregisterReceiver()?
             	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1594)
             	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1374)
             	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1614)
             	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1580)
             	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1568)
             	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:668)
             	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:916)
             	at com.razorpay.CheckoutPresenterImpl.onLoad(CheckoutPresenterImpl.java:907)
             	at com.razorpay.J$_0_.secure(CheckoutBridge.java:27)
             	at com.razorpay.CheckoutPresenterImpl.executeWebViewCallback(CheckoutPresenterImpl.java:1370)
             	at com.razorpay.CheckoutPresenterImpl.access$700(CheckoutPresenterImpl.java:55)
             	at com.razorpay.b$_f_.run(CheckoutPresenterImpl.java:1355)
             	at android.os.Handler.handleCallback(Handler.java:938)
             	at android.os.Handler.dispatchMessage(Handler.java:99)
             	at android.os.Looper.loop(Looper.java:223)
             	at android.app.ActivityThread.main(ActivityThread.java:7656)
             	at java.lang.reflect.Method.invoke(Native Method)
             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by PembaTamang** [comment]
same issue here.

**Comment by vivekshindhe** [comment]
Hey folks, this issue has been resolved in the latest build. Please update the version of the SDK to the latest one. You can find the latest version [here](https://razorpay.com/docs/payments/payment-gateway/android-integration/standard#list-of-razorpay-android-standard-sdk-versions-last). Closing this ticket. Please comment if you folks see the issue or create another issue. Thanks.
