### ISSUE TITLE
SDK version : 1.6.32 Fatal Exception: java.lang.NoSuchFieldError: No static field err_name_not_resolved_title of type I in class Lcom/razorpay/R$string; or its superclasses 

### ISSUE THREAD

**Issue by lovemhjn** [razorpay/razorpay-android-sample-app#359]
Sdk version : 1.6.32
Fatal Exception: java.lang.NoSuchFieldError: No static field err_name_not_resolved_title of type I in class Lcom/razorpay/R$string; or its superclasses (declaration of 'com.razorpay.R$string' appears in /data/app/~~XRM-IB2Y76xeuu_ymns-5A==/com.example.app.-avDgd0T0S3H2NakkKKV-nQ==/base.apk!classes4.dex)
       at com.razorpay.CheckoutPresenterImpl.showLoaderDialog(CheckoutPresenterImpl.java:535)
       at com.razorpay.PrimaryWebViewClient.onReceivedError(PrimaryWebViewClient.java:30)
       at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:339)
       at qI0.c(chromium-TrichromeWebViewGoogle.aab-stable-519513633:159)
       at Qa.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-519513633:186)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by vivekshindhe** [comment]
@lovemhjn This has been resolved in the latest release 1.6.33. [Link](https://razorpay.com/docs/payments/payment-gateway/android-integration/standard/#list-of-razorpay-android-standard-sdk-versions-last)
