### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by SagarBChauhan** [razorpay/razorpay-android-sample-app#377]
## Description
Facing the following crash when trying to checkout on a device with Android version 14 after updating the targetSdkVersion from 33 to 34. I’m encountering the same issue in both of my apps.

> java.lang.SecurityException: findPanditji.findPanditji: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
>                  	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
>                  	at android.os.Parcel.createException(Parcel.java:3053)
>                  	at android.os.Parcel.readException(Parcel.java:3036)
>                  	at android.os.Parcel.readException(Parcel.java:2978)
>                  	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
>                  	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
>                  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
>                  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
>                  	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
>                  	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:938)
>                  	at com.razorpay.CheckoutPresenterImpl.access$500(CheckoutPresenterImpl.java:56)
>                  	at com.razorpay.G$_X_.onFinish(CheckoutPresenterImpl.java:917)
>                  	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
>                  	at android.os.Handler.dispatchMessage(Handler.java:106)
>                  	at android.os.Looper.loopOnce(Looper.java:230)
>                  	at android.os.Looper.loop(Looper.java:319)
>                  	at android.app.ActivityThread.main(ActivityThread.java:8893)
>                  	at java.lang.reflect.Method.invoke(Native Method)
>                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
>                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

## Razorpay SDK Version :
`com.razorpay:checkout:1.6.29`

## Android OS Version :
Android version 14 

### What you did:
Updated my project's targetSdkVersion from 33 to 34

### What happened:
Facing app crash while trying to checkout.

## Steps To Reproduce

1. Set `targetSdkVersion` to 34 in the `build.gradle(app)` file.
2. Run your application on a device with Android version 14.
3. Proceed to the checkout. The Razorpay checkout page will open, but it will crash after 1-2 seconds, returning a checkout error.

### Suggested solution:

As per the new update, either `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED` must be specified when a receiver is not exclusively registered for system broadcasts. I encountered this issue with other broadcast receivers in my apps, and passing `Context.RECEIVER_NOT_EXPORTED` as the second parameter in `registerReceiver()` helped resolve the problem. Applying a similar fix on Razorpay's end might also solve this issue.

Here is an example of my solution:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
    registerReceiver(broadcastReceiver, new IntentFilter(AppConstants.MA_VIDEO_RECEIVER), Context.RECEIVER_NOT_EXPORTED);
} else {
    registerReceiver(broadcastReceiver, new IntentFilter(AppConstants.MA_VIDEO_RECEIVER));
}
```

**Comment by SagarBChauhan** [comment]
## Description
I am facing the following crash when trying to checkout on a device with Android version API "VanillaIceCream" after setting the targetSdkVersion & compileSdkVersion 34. on 
> java.lang.SecurityException: findPanditji.findPanditji: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
>                  	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
>                  	at android.os.Parcel.createException(Parcel.java:3053)
>                  	at android.os.Parcel.readException(Parcel.java:3036)
>                  	at android.os.Parcel.readException(Parcel.java:2978)
>                  	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
>                  	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
>                  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
>                  	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
>                  	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
>                  	at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:938)
>                  	at com.razorpay.CheckoutPresenterImpl.access$500(CheckoutPresenterImpl.java:56)
>                  	at com.razorpay.G$_X_.onFinish(CheckoutPresenterImpl.java:917)
>                  	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
>                  	at android.os.Handler.dispatchMessage(Handler.java:106)
>                  	at android.os.Looper.loopOnce(Looper.java:230)
>                  	at android.os.Looper.loop(Looper.java:319)
>                  	at android.app.ActivityThread.main(ActivityThread.java:8893)
>                  	at java.lang.reflect.Method.invoke(Native Method)
>                  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
>                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

## Razorpay SDK Version :
`com.razorpay:checkout:1.6.29`

## Android OS Version :
Android version 14 

### What you did:
Updated my project's targetSdkVersion from 33 to 34

### What happened:
Facing app crash while trying to checkout.

## Steps To Reproduce

1. Set `targetSdkVersion` to 34 in the `build.gradle(app)` file.
2. Run your application on a device with Android version 14.
3. Proceed to the checkout. The Razorpay checkout page will open, but it will crash after 1-2 seconds, returning a checkout error.

### Suggested solution:

As per the new update, either `RECEIVER_EXPORTED` or `RECEIVER_NOT_EXPORTED` must be specified when a receiver is not exclusively registered for system broadcasts. I encountered this issue with other broadcast receivers in my apps, and passing `Context.RECEIVER_NOT_EXPORTED` as the second parameter in `registerReceiver()` helped resolve the problem. Applying a similar fix on Razorpay's end might also solve this issue.

Here is an example of my solution:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
    registerReceiver(broadcastReceiver, new IntentFilter(AppConstants.MA_VIDEO_RECEIVER), Context.RECEIVER_NOT_EXPORTED);
} else {
    registerReceiver(broadcastReceiver, new IntentFilter(AppConstants.MA_VIDEO_RECEIVER));
}
```
### Description
I am facing the following crash when trying to checkout on a device with Android version API "VanillaIceCream" after setting the targetSdkVersion & compileSdkVersion 34. on 

java.lang.SecurityException: findPanditji.findPanditji: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
at android.os.Parcel.createException(Parcel.java:3053)
at android.os.Parcel.readException(Parcel.java:3036)
at android.os.Parcel.readException(Parcel.java:2978)
at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:938)
at com.razorpay.CheckoutPresenterImpl.access$500(CheckoutPresenterImpl.java:56)
at com.razorpay.G$X.onFinish(CheckoutPresenterImpl.java:917)
at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8893)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Razorpay SDK Version :
com.razorpay:checkout:1.6.29

Android OS Version :
Android version 14

What you did:
Updated my project's targetSdkVersion from 33 to 34

What happened:
Facing app crash while trying to checkout.

Steps To Reproduce
Set targetSdkVersion to 34 in the build.gradle(app) file.
Run your application on a device with Android version 14.
Proceed to the checkout. The Razorpay checkout page will open, but it will crash after 1-2 seconds, returning a checkout error.
Suggested solution:
As per the new update, either RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED must be specified when a receiver is not exclusively registered for system broadcasts. I encountered this issue with other broadcast receivers in my apps, and passing Context.RECEIVER_NOT_EXPORTED as the second parameter in registerReceiver() helped resolve the problem. Applying a similar fix on Razorpay's end might also solve this issue.

Here is an example of my solution:

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
    registerReceiver(broadcastReceiver, new IntentFilter(AppConstants.MA_VIDEO_RECEIVER), Context.RECEIVER_NOT_EXPORTED);
} else {
    registerReceiver(broadcastReceiver, new IntentFilter(AppConstants.MA_VIDEO_RECEIVER));
}

![image_2024_08_26T07_58_31_988Z](https://github.com/user-attachments/assets/6b7bf040-7914-43cb-a415-67d34dca2d47)

**Comment by SagarBChauhan** [comment]
Upgrading the dependency to `com.razorpay:checkout:1.6.40` solved the issue.
