### ISSUE TITLE
App crashes when attempting to open Checkout page !

### ISSUE THREAD

**Issue by sans07** [razorpay/razorpay-android-sample-app#38]
The error is : 

java.lang.IllegalAccessError: Illegal class access: 'com.razorpay.Q$$U_' attempting to access 'com.razorpay.Q$$U_$5' (declaration of 'com.razorpay.Q$$U_' appears in /data/data/com.protomake/cache/.    )
                                                                 at com.razorpay.Q$$U_.Q_$2$(:8085)
                                                                 at com.razorpay.Q$$U_.d__1_(:341)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.razorpay.E$_6$.G__G_(:33048)
                                                                 at com.razorpay.CheckoutActivity.onCreate(:30038)
                                                                 at android.app.Activity.performCreate(Activity.java:6005)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:176)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5576)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

I couldn't find any solution what was the issue here ?

**Comment by hariramsvnit** [comment]
@sans07 Never faced this crash earlier, what is the frequency of this crash and is there any specific steps to reproduce it?

**Comment by hariramsvnit** [comment]
@sans07 Also, are you using JAVA8  with jackoptions for lambda function support?

**Comment by sans07** [comment]
@hariramsvnit  i have used  

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

i was using  v1.3.4 earlier and tested it in test credentials it worked perfect but after the release update to 1.4.0 am facing this issue 

When i try to pay the checkout page never opens it crashes every time when i try to open !

**Comment by sans07** [comment]
@hariramsvnit  

This error also found  E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport !

**Comment by hariramsvnit** [comment]
@sans07 I have checked in sample app by enabling java8, I am facing same crash in `1.4.0` and `1.3.4` both, java8 is not supported with our SDK right now, we will try to add support for same in the future.

**Comment by sans07** [comment]
@hariramsvnit  ok then as of now i won't be able to use SDK if i enable Java8 right ?

**Comment by hariramsvnit** [comment]
@sans07 Yes, correct.

**Comment by thekalinga** [comment]
@sans07 Jack is not supported anymore by Android. If you need to use Java8, use 3.0.0-beta5 version of android.
