### ISSUE TITLE
Unable to start activity ComponentInfo{com.rnei.scraptapb2b/com.razorpay.CheckoutActivity}

### ISSUE THREAD

**Issue by binkkatal** [razorpay/razorpay-android-sample-app#50]
Have followed the same example as the sample app and i am getting this error

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rnei.scraptapb2b/com.razorpay.CheckoutActivity}: java.lang.ArrayIndexOutOfBoundsException: length=39; index=39
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                       Caused by: java.lang.ArrayIndexOutOfBoundsException: length=39; index=39
                                                                          at com.razorpay.K$$z$.$$d()
                                                                          at com.razorpay.K$$z$.$$a()
                                                                          at com.razorpay.K$$z$.<clinit>(:67)
                                                                          at com.razorpay.K$$z$.R$$r_()
                                                                          at com.razorpay.D$_X_.G__G_(:174)
                                                                          at com.razorpay.l_$w$.G__G_(:351)
                                                                          at com.razorpay.CheckoutActivity.onCreate(:69)
                                                                          at android.app.Activity.performCreate(Activity.java:6679)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by binkkatal** [comment]
public class RazorpayPayment extends AppCompatActivity implements PaymentResultListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_razorpay_payment);
        Button button = (Button) findViewById(R.id.pay);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                final Activity activity = RazorpayPayment.this;

                final Checkout co = new Checkout();

                try {
                    JSONObject options = new JSONObject();
                    options.put("name", "Razorpay Corp");
                    options.put("description", "Demoing Charges");
                    //You can omit the image option to fetch the image from dashboard
                    options.put("image", "https://rzp-mobile.s3.amazonaws.com/images/rzp.png");
                    options.put("currency", "INR");
                    options.put("amount", "100");

                    JSONObject preFill = new JSONObject();
                    preFill.put("email", "test@razorpay.com");
                    preFill.put("contact", "9876543210");

                    options.put("prefill", preFill);

                    co.open(activity, options);
                } catch (Exception e) {
                    Toast.makeText(activity, "Error in payment: " + e.getMessage(), Toast.LENGTH_SHORT)
                            .show();
                    e.printStackTrace();
                }

            }
        });
    }

    @Override
    public void onPaymentSuccess(String s) {

    }

    @Override
    public void onPaymentError(int i, String s) {

    }
}

**Comment by binkkatal** [comment]
@hariramsvnit the crash is persistent .
It always occurs when the button for  payment is pressed.

Does it has anything to do with the gradle configurations and other dependencies ?
As i tried the same code in a freshly created sample app and it worked.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=39; index=39
at com.razorpay.K$$z$.$$d()
at com.razorpay.K$$z$.$$a()
at com.razorpay.K$$z$.(:67)
at com.razorpay.K$$z$.R$$r_()
at com.razorpay.D$X.G__G_(:174)
at com.razorpay.l_$w$.G__G_(:351)
at com.razorpay.CheckoutActivity.onCreate(:69)

```

However , i wonder why is it crashing in the checkout activity ?

**Comment by hariramsvnit** [comment]
@binkkatal Looks like the issue might be related to some configuration or dependency on your side, Please send build.gradle file to support@razorpay.com and I will look into it.

**Comment by hariramsvnit** [comment]
@binkkatal Our SDK doesn't support `jackOptions` and Java 8.

**Comment by Suganyasrii** [comment]
For me also am getting the below issue,Please suggest how to resolve this issue?
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.sample/com.razorpay.CheckoutActivity}: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.app.sample/cache: open failed: EISDIR (Is a directory)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                    Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.app.sample/cache: open failed: EISDIR (Is a directory)
                                                                       at com.razorpay.K$$z$.<clinit>(:393)
                                                                       at com.razorpay.E$_j$.G__G_(:174)
                                                                       at com.razorpay.l_$w$.a_$P$(:345)
                                                                       at com.razorpay.CheckoutActivity.onCreate(:71)
                                                                       at android.app.Activity.performCreate(Activity.java:6245)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                    Caused by: java.io.FileNotFoundException: /data/user/0/com.app.sample/cache: open failed: EISDIR (Is a directory)
                                                                       at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                       at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                       at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                       at com.razorpay.K$$z$.<clinit>(:142)
                                                                       at com.razorpay.E$_j$.G__G_(:174) 
                                                                       at com.razorpay.l_$w$.a_$P$(:345) 
                                                                       at com.razorpay.CheckoutActivity.onCreate(:71) 
                                                                       at android.app.Activity.performCreate(Activity.java:6245) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                    Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
                                                                       at libcore.io.Posix.open(Native Method)
                                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                       at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                       at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                       at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                       at com.razorpay.K$$z$.<clinit>(:142) 
                                                                       at com.razorpay.E$_j$.G__G_(:174) 
                                                                       at com.razorpay.l_$w$.a_$P$(:345) 
                                                                       at com.razorpay.CheckoutActivity.onCreate(:71) 
                                                                       at android.app.Activity.performCreate(Activity.java:6245) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by hariramsvnit** [comment]
@Suganyasrii We are working on the issue right now, we plan to support Java 8, I will update you soon.

**Comment by Suganyasrii** [comment]
Hi Hari,
    Thanks for your info, May I know when new version will release?

Regards,

*Suganya M*
Android Developer

*Nextbrain Technologies Pvt Ltd*,
#44, 2nd floor, 1st cross, 2nd main, Prasanth extension, Whitefield,
Bangalore - 560066.
Mobile: +919962828791 |  www.nextbrainitech.com


DISCLAIMER: The information contained in this message (including any
attachments) is confidential and may be privileged. If you have received it
by mistake please notify the sender by return e-mail and permanently delete
this message and any attachments from your system. Any dissemination, use,
review, distribution, printing or copying of this message in whole or in
part is strictly prohibited. Please note that e-mails are susceptible to
change. Nextbrain Technologies Pvt Ltd (including its group companies)
shall not be liable for the improper or incomplete transmission of the
information contained in this email.

On Mon, Apr 9, 2018 at 5:31 PM, Hari Ram Choudhary <notifications@github.com

**Comment by hariramsvnit** [comment]
@Suganyasrii I am working on the issue will release the SDK once the issue is fixed, I am hoping that we will be able to release the SDK by tomorrow EOD.

**Comment by hariramsvnit** [comment]
@Suganyasrii 

I have tried SDK version `1.4.7` while java 8 was enabled in the app and it's working fine. I was facing build error but adding `android.enableD8.desugaring = true` to `gradle.properties` file solved build error form me. 

I am using `compileSdkVersion` `27` and gradle version `4.4`.

Note: Here I was using Java 8 provided by Google (https://developer.android.com/studio/write/java8-support.html)

**Comment by binkkatal** [comment]
@hariramsvnit tried `android.enableD8.desugaring = true` but still no luck .
Are you thinking to support jack options ?

**Comment by hariramsvnit** [comment]
@binakkatal Sorry, we are not planning to support jack options as it has been deprecated by Google.

**Comment by Suganyasrii** [comment]
@binkkatal 

  Instead of using jack option (android.enableD8.desugaring = true) use this,
app gradle - >apply plugin: 'me.tatarka.retrolambda'
project gradle->  classpath 'me.tatarka:gradle-retrolambda:3.2.3'
i tried its working 
 
 ,

**Comment by binkkatal** [comment]
@Suganyasrii  i'll try you approach

**Comment by hiten** [comment]
@hariramsvnit I tried using android.enableD8.desugaring = true but I don't know why its increasing my build time by 14-15 minutes. With retorlambda I am able to compile my project within 1 minute. I shifted my complete project to kotlin so I am planning to remove retrolambda but I am stuck now.
