### ISSUE TITLE
Couldn't find outer class com/razorpay/Y_$B$ of com/razorpay/Y_$B$$5

### ISSUE THREAD

**Issue by khemrajsharma** [razorpay/razorpay-android-sample-app#54]
Exception in thread "main" java.lang.NullPointerException: Couldn't find outer class com/razorpay/Y_$B$ of com/razorpay/Y_$B$$5
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1079)
	at com.google.devtools.build.android.desugar.ClassVsInterface.isOuterInterface(ClassVsInterface.java:56)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitOuterClass(InterfaceDesugaring.java:246)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:638)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)

**Comment by VisheshVadhera** [comment]
I too am getting this error after upgrading the AGP to 4.4 from 3.2. Do you guys have any fix for this?

**Comment by hariramsvnit** [comment]
@khemrajsharma @VisheshVadhera Can you please try [this](https://github.com/razorpay/razorpay-android-sample-app/issues/50#issuecomment-379996496) solution.

**Comment by khemrajsharma** [comment]
@VisheshVadhera Yes i have solved this. Please follow the SO link which i answered.
https://stackoverflow.com/questions/50344132/couldnt-find-outer-class-com-razorpay-y-b-of-com-razorpay-y-b5

**Comment by VisheshVadhera** [comment]
@hariramsvnit Is it possible for you to update the supported version of Java to Java8? The solution suggested in the other post is only a short term fix. 

Due to the fact that the razorpay sdk doesn't support Java 8, we are stuck on an older version of the AGP and hence unable to move ahead with times.
