### ISSUE TITLE
razorpay checkoutActivity crash on Oreo

### ISSUE THREAD

**Issue by krishnarama** [razorpay/razorpay-android-sample-app#58]
we are facing crash issue on Oreo devices suddenly with the below error.

05-31 08:15:18.577 18958-18958/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smileyserve, PID: 18958
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.razorpay.RzpAssist.onProgressChanged(int)' on a null object reference
        at com.razorpay.CheckoutActivity$10.onProgressChanged(:246)
        at com.android.webview.chromium.Ap.onProgressChanged(WebViewContentsClientAdapter.java:45)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:79)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6637)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    

please suggest the solution. we are using gradle dependency com.razorpay:checkout:1.3.4

**Comment by hariramsvnit** [comment]
@krishnarama what's the version of the SDK you are using?

**Comment by sumedht** [comment]
Closing as no response from @krishnarama
