### ISSUE TITLE
Unable to start activity ComponentInfo{com.example.rozarpay/com.razorpay.CheckoutActivity}: java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Yugalmodi** [razorpay/razorpay-android-sample-app#63]
FATAL EXCEPTION: main
                                                                  Process: com.example.rozarpay, PID: 18776
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.rozarpay/com.razorpay.CheckoutActivity}: java.lang.StringIndexOutOfBoundsException: length=3; index=8
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
                                                                      at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                      at android.os.Looper.loop(Looper.java:166)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                                   Caused by: java.lang.StringIndexOutOfBoundsException: length=3; index=8
                                                                      at java.lang.String.substring(String.java:1971)
                                                                      at com.razorpay.E$_j$.Q_$2$(:30204)
                                                                      at com.razorpay.CheckoutActivity.onCreate(:28048)
                                                                      at android.app.Activity.performCreate(Activity.java:7372)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
                                                                      at android.app.ActivityThread.-wrap12(Unknown Source:0) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                                      at android.os.Looper.loop(Looper.java:166) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7425) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by hariramsvnit** [comment]
@Yugalmodi Can you please tell frequency of the crash and steps to reproduce the crash?

**Comment by Yugalmodi** [comment]
Hi @hariramsvnit ,
My problem get resolved after change API key.

**Comment by hariramsvnit** [comment]
@Yugalmodi Cool.
