### ISSUE TITLE
getting runtime error in checkout 

### ISSUE THREAD

**Issue by ratneshsinghparihar** [razorpay/razorpay-android-sample-app#84]
10-22 20:58:55.352 3948-3948/com.sportssage E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sportssage, PID: 3948
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sportssage/com.razorpay.CheckoutActivity}: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/com.sportssage-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sportssage-1/lib/x86, /data/app/com.sportssage-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.d__1_" on path: DexPathList[[zip file "/data/app/com.sportssage-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sportssage-1/lib/x86, /data/app/com.sportssage-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.razorpay.Q$$U_.d__1_(:1100)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.razorpay.I$_e_.<clinit>(:204)
        at com.razorpay.b__J_.a_$P$(:182)
        at com.razorpay.O_$B_.G__G_(:380)
        at com.razorpay.c__C_.onCreate(:79)
        at com.razorpay.CheckoutActivity.onCreate(:13)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: com.razorpay.d__1_
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 20 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by ratneshsinghparihar** [comment]
In Debug mode its wokring properly , but on assembleRelease it crashes

**Comment by gauravk95** [comment]
Probably, you need to add proguard rules(so that the files don't get obfuscated) in your **app\proguard-rules.pro**

Add this, I guess it will work then


-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
-keepattributes JavascriptInterface
-keepattributes *Annotation*
-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}
-optimizations !method/inlining/*
-keepclasseswithmembers class * {
  public void onPayment*(...);
}

**Comment by sumedht** [comment]
@ratneshsinghparihar @gauravk95 this issue still exist? Which version of SDK u r using?

**Comment by raikk** [comment]
i had same issues. 
My android sdk version 28
react-native-razorpay version 2.1.23

I add this in app\proguard-rules.pro

```
-keepattributes *Annotation*
-dontwarn com.razorpay.**
-keep class com.razorpay.** {*;}
-optimizations !method/inlining/
-keepclasseswithmembers class * {
public void onPayment*(...);
}
```

then it worked

**Comment by sumedht** [comment]
@ratneshsinghparihar @gauravk95 Update to our latest SDK version. R u still getting this issue?

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
