### ISSUE TITLE
App Crash on back pressed

### ISSUE THREAD

**Issue by jrsadik7** [razorpay/razorpay-android-sample-app#97]
2019-02-14 20:53:02.980 2440-2440/E/InputEventSender: Exception dispatching finished signal.
2019-02-14 20:53:02.980 2440-2440/ E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2019-02-14 20:53:02.986 2440-2440/ E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at com.razorpay.l__d$.backPressed(:17076)
        at com.razorpay.r_$Z$.backPressed(:148)
        at com.razorpay.b__J_.onBackPressed(:148)
        at com.razorpay.CheckoutActivity.onBackPressed(:5)
        at android.app.Activity.onKeyUp(Activity.java:2871)
        at android.view.KeyEvent.dispatch(KeyEvent.java:3384)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3172)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:492)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5110)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5072)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4736)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4793)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4938)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3163)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2665)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2656)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3140)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)

 at com.razorpay.l__d$.backPressed(:17076)
        at com.razorpay.r_$Z$.backPressed(:148)
        at com.razorpay.b__J_.onBackPressed(:148)
        at com.razorpay.CheckoutActivity.onBackPressed(:5)
        at android.app.Activity.onKeyUp(Activity.java:2871)
        at android.view.KeyEvent.dispatch(KeyEvent.java:3384)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3172)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:492)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5110)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5072)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4736)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4793)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4938)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3163)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2665)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2656)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3140)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)

**Comment by sumedht** [comment]
@jrsadik7 We are looking into this issue. Can you provide steps to reproduce it?
Also, want to know which Chrome version ur using?

**Comment by umanghome** [comment]
@jrsadik7 - Would you be willing to send your app to us? We are unable to reproduce this.

**Comment by sidx1024** [comment]
@jrsadik7 - We have released a new SDK which fixes this issue `com.razorpay:checkout:1.5.3`.

**Comment by dk-slicepay** [comment]
Have you guys released V1.5.3 ?

**Comment by jrsadik7** [comment]
@sidx1024 not able to see release notes for com.razorpay:checkout:1.5.3 in the release page
 https://github.com/razorpay/razorpay-android-sample-app/releases  can you please confirm on this.

**Comment by Sridharan0** [comment]
After the version change to 1.5.3, I'm facing an issue in cancel payment by pressing the back button and it takes lots of time to cancel

**Comment by vivekshindhe** [comment]
@Sridharan0 Please update to v1.6.7.

**Comment by Sridharan0** [comment]
That helps man.. thanks.

> @Sridharan0 Please update to v1.6.7.
